export const worksFilters = [
  { id: "all", label: "All" },
  { id: "photography", label: "Photography" },
  { id: "cinematography", label: "Cinematography" },
];

export const worksItems = [
  {
    id: "revv-campaign-visual",
    category: "photography",
    kind: "image",
    className: "card-feature",
    typeLabel: "Photography",
    title: "REVV Campaign Visual",
    imageSrc: "/works/image/REVV.jpg",
    imageAlt: "REVV 캠페인 대표 이미지",
  },
  {
    id: "moneyism-ai-teaser",
    category: "cinematography",
    kind: "video",
    className: "card-video",
    typeLabel: "Cinematography",
    title: "Moneyism AI Teaser",
    videoSrc: "/works/video/moneyism-teaser.webm",
    href: "https://www.youtube.com/shorts/aocSdGRn2nI",
    ariaLabel: "Moneyism AI Teaser 영상 열기",
  },
  {
    id: "saerom-herbal-beauty-cut",
    category: "photography",
    kind: "image",
    className: "card-dark card-photo",
    typeLabel: "Photography",
    title: "Saerom Herbal Beauty Cut",
    imageSrc: "/works/image/saerom-black-goat-beauty-cut.jpg",
    imageAlt: "새롬한방 흑염소진액 뷰티컷",
  },
  {
    id: "gen-ai-seoul-opening",
    category: "cinematography",
    kind: "video",
    className: "card-video-inline",
    typeLabel: "Cinematography",
    title: "GEN AI SEOUL 2025 Opening",
    videoSrc: "/works/video/gen-ai-seoul-opening.webm",
    href: "https://youtu.be/XtWxe_S7nt4?si=CIl-Scs84aEHoB0q",
    ariaLabel: "GEN AI SEOUL 2025 오프닝 영상 열기",
  },
  {
    id: "kbs-2025-promo-film",
    category: "cinematography",
    kind: "video",
    className: "card-soft card-video-wide",
    typeLabel: "Cinematography",
    title: "KBS 2025 Promo Film",
    videoSrc: "/works/video/kbs-happy-future.webm",
    href: "https://youtu.be/av9kFpHjj08?si=dofwsG8FSgxsT6oi",
    ariaLabel: "KBS 홍보 영상 열기",
  },
  {
    id: "naver-webtoon-ai-teaser",
    category: "cinematography",
    kind: "video",
    className: "card-video-tall",
    typeLabel: "Cinematography",
    title: "Naver Webtoon AI Teaser",
    videoSrc: "/works/video/naver-webtoon-ai-teaser.webm",
    href: "https://www.youtube.com/shorts/Ud1OrxerwE4",
    ariaLabel: "네이버웹툰 별정직공무원 AI 티저 열기",
  },
];
