export const worksFilters = [
  { id: "all", label: "All" },
  { id: "photography", label: "이미지" },
  { id: "cinematography", label: "영상" },
];

export const worksItems = [
  {
    id: "premium-bachelor-kimchi-detail",
    detailSlug: "premium-bachelor-kimchi",
    category: "photography",
    kind: "image",
    aspect: "9:16",
    className: "card-photo",
    typeLabel: "이미지",
    title: "정성곳간 프리미엄 총각김치 상세페이지",
    imageSrc: "/works/image/premium-bachelor-kimchi-thumbnail.webp",
    imageAlt: "정성곳간 프리미엄 총각김치 상세페이지 대표 이미지",
  },
  {
    id: "lefleur-oral-spray-detail",
    detailSlug: "lefleur-oral-spray",
    category: "photography",
    kind: "image",
    aspect: "9:16",
    className: "card-photo",
    typeLabel: "이미지",
    title: "르플레르 구강 스프레이 상세페이지",
    imageSrc: "/works/image/lefleur-oral-spray-thumbnail.webp",
    imageAlt: "르플레르 구강 스프레이 상세페이지 대표 이미지",
  },
  {
    id: "korea-university-volunteer-promo-film",
    category: "cinematography",
    kind: "video",
    aspect: "16:9",
    className: "card-video-inline",
    typeLabel: "영상",
    title: "고려대학교 봉사단 홍보 영상",
    videoSrc: "/works/video/korea-university-volunteer-promo-film.webm",
    href: "https://drive.google.com/file/d/1y3bVT9aqwmkOiJ6VZrqN328p_LRvb2rK/view?usp=sharing",
    ariaLabel: "고려대학교 봉사단 홍보 영상 열기",
  },
  {
    id: "liberi-gangnam-screen-film",
    category: "cinematography",
    kind: "video",
    aspect: "9:16",
    className: "card-video-tall",
    typeLabel: "영상",
    title: "리베리 의원 강남점 스크린 영상",
    videoSrc: "/works/video/liberi-gangnam-screen-film.webm",
    href: "https://drive.google.com/file/d/1eXKTgP7DWH3jecQaOGKhT0Un3d9tvdXB/view?usp=sharing",
    ariaLabel: "리베리 의원 강남점 스크린 영상 열기",
  },
  {
    id: "moneyism-ai-teaser",
    category: "cinematography",
    kind: "video",
    aspect: "9:16",
    className: "card-video",
    typeLabel: "영상",
    title: "샤MONEY즘 AI 실사화",
    videoSrc: "/works/video/moneyism-teaser.webm",
    href: "https://www.youtube.com/shorts/aocSdGRn2nI",
    ariaLabel: "샤MONEY즘 AI 실사화 영상 열기",
  },
  {
    id: "saerom-herbal-beauty-cut",
    detailSlug: "saerom-black-goat-beauty-cut",
    category: "photography",
    kind: "image",
    aspect: "4:3",
    className: "card-dark card-photo",
    typeLabel: "이미지",
    title: "새롬한방 흑염소진액 뷰티컷",
    imageSrc: "/works/image/saerom-black-goat-beauty-cut.jpg",
    imageAlt: "새롬한방 흑염소진액 뷰티컷",
  },
  {
    id: "hailuo-promo-film",
    category: "cinematography",
    kind: "video",
    aspect: "9:16",
    className: "card-video-tall",
    typeLabel: "영상",
    title: "하이루오 홍보 영상",
    videoSrc: "/works/video/hailuo-promo-film.webm",
    href: "https://youtube.com/shorts/LKwG2H8YH34?feature=share",
    ariaLabel: "하이루오 홍보 영상 열기",
  },
  {
    id: "revv-campaign-visual",
    detailSlug: "revv",
    category: "photography",
    kind: "image",
    aspect: "9:16",
    className: "card-feature",
    typeLabel: "이미지",
    title: "REVV 올리비아로렌 브랜드 런웨이",
    imageSrc: "/works/image/REVV.jpg",
    imageAlt: "REVV 올리비아로렌 브랜드 런웨이 대표 이미지",
  },
  {
    id: "gen-ai-seoul-opening",
    category: "cinematography",
    kind: "video",
    aspect: "16:9",
    className: "card-video-inline",
    typeLabel: "영상",
    title: "GEN AI SEOUL 2025 오프닝",
    videoSrc: "/works/video/gen-ai-seoul-opening.webm",
    href: "https://youtu.be/XtWxe_S7nt4?si=CIl-Scs84aEHoB0q",
    ariaLabel: "GEN AI SEOUL 2025 오프닝 영상 열기",
  },
  {
    id: "kbs-2025-promo-film",
    category: "cinematography",
    kind: "video",
    aspect: "16:9",
    className: "card-soft card-video-wide",
    typeLabel: "영상",
    title: "KBS 2025 홍보 영상",
    videoSrc: "/works/video/kbs-happy-future.webm",
    href: "https://youtu.be/av9kFpHjj08?si=dofwsG8FSgxsT6oi",
    ariaLabel: "KBS 홍보 영상 열기",
  },
  {
    id: "naver-webtoon-ai-teaser",
    category: "cinematography",
    kind: "video",
    aspect: "9:16",
    className: "card-video-tall",
    typeLabel: "영상",
    title: "네이버 웹툰 별정직 공무원 AI 실사화",
    videoSrc: "/works/video/naver-webtoon-ai-teaser.webm",
    href: "https://www.youtube.com/shorts/Ud1OrxerwE4",
    ariaLabel: "네이버웹툰 별정직공무원 AI 티저 열기",
  },
  {
    id: "boneld-greenjuice-insert-ad",
    category: "cinematography",
    kind: "video",
    aspect: "16:9",
    className: "card-video-inline",
    typeLabel: "영상",
    title: "보넬드 그린주스 인서트 광고",
    videoSrc: "/works/video/boneld-greenjuice-insert-ad.webm",
    href: "https://youtu.be/qv_ktLnoJso",
    ariaLabel: "보넬드 그린주스 인서트 광고 영상 열기",
  },
  {
    id: "lefleur-brand-film",
    category: "cinematography",
    kind: "video",
    aspect: "16:9",
    className: "card-video-inline",
    typeLabel: "영상",
    title: "르플레르 브랜드 영상",
    videoSrc: "/works/video/lefleur-brand-film.webm",
    href: "https://youtu.be/oKseC_3o-ao",
    ariaLabel: "르플레르 브랜드 영상 열기",
  },
  {
    id: "sbs-special-docu-omega",
    category: "cinematography",
    kind: "video",
    aspect: "16:9",
    className: "card-video-inline",
    typeLabel: "영상",
    title: "SBS 일요특선 다큐 오메가",
    videoSrc: "/works/video/sbs-special-docu-omega.webm",
    href: "https://drive.google.com/file/d/1wv3QVQ5ceFSaQKbHRKE-fF0uSLn4JaI6/view?usp=sharing",
    ariaLabel: "SBS 일요특선 다큐 오메가 영상 열기",
  },
  {
    id: "mamakoreana-brand-film",
    category: "cinematography",
    kind: "video",
    aspect: "16:9",
    className: "card-video-inline",
    typeLabel: "영상",
    title: "마마코레아나 브랜드 영상",
    videoSrc: "/works/video/mamakoreana-brand-film.webm",
    href: "https://youtu.be/VoePEABTOyM",
    ariaLabel: "마마코레아나 브랜드 영상 열기",
  },
  {
    id: "mbc-take-care-of-mother-lee-miyoung",
    category: "cinematography",
    kind: "video",
    aspect: "16:9",
    className: "card-video-inline",
    typeLabel: "영상",
    title: "MBC 엄마를 부탁해 이미영편",
    videoSrc: "/works/video/mbc-take-care-of-mother-lee-miyoung.webm",
    href: "https://youtu.be/46krFCXZFWI",
    ariaLabel: "MBC 엄마를 부탁해 이미영편 영상 열기",
  },
  {
    id: "channel-a-secret-of-survival-27",
    category: "cinematography",
    kind: "video",
    aspect: "16:9",
    className: "card-video-inline",
    typeLabel: "영상",
    title: "채널A 생존의 비밀 27회",
    videoSrc: "/works/video/channel-a-secret-of-survival-27.webm",
    href: "https://youtu.be/5SsQfclqW0o",
    ariaLabel: "채널A 생존의 비밀 27회 영상 열기",
  },
  {
    id: "channel-a-secret-of-survival-obesity",
    category: "cinematography",
    kind: "video",
    aspect: "16:9",
    className: "card-video-inline",
    typeLabel: "영상",
    title: "채널A 생존의 비밀 비만편",
    videoSrc: "/works/video/channel-a-secret-of-survival-obesity.webm",
    href: "https://youtu.be/P7mBKlrZuGE",
    ariaLabel: "채널A 생존의 비밀 비만편 영상 열기",
  },
  {
    id: "hongdong-secret-jindangbowon-insert-ad",
    category: "cinematography",
    kind: "video",
    aspect: "16:9",
    className: "card-video-inline",
    typeLabel: "영상",
    title: "홍동비책 진당보원 인서트 브랜드 광고",
    videoSrc: "/works/video/hongdong-secret-jindangbowon-insert-ad.webm",
    href: "https://youtu.be/8631jL9TUEo",
    ariaLabel: "홍동비책 진당보원 인서트 브랜드 광고 영상 열기",
  },
  {
    id: "richcoco-beauty-cut",
    detailSlug: "richcoco",
    category: "photography",
    kind: "image",
    aspect: "4:3",
    className: "card-photo",
    typeLabel: "이미지",
    title: "보넬드 리치코코 뷰티컷",
    imageSrc: "/works/image/리치코코_섬네일.webp",
    imageAlt: "리치코코 뷰티컷 대표 이미지",
  },
  {
    id: "galbitsal-beauty-cut",
    detailSlug: "galbitsal",
    category: "photography",
    kind: "image",
    aspect: "16:9",
    className: "card-photo",
    typeLabel: "이미지",
    title: "정성곳간 갈빗살 뷰티컷",
    imageSrc: "/works/image/갈빗살_섬네일.webp",
    imageAlt: "갈빗살 뷰티컷 대표 이미지",
  },
  {
    id: "blueberry-beauty-cut",
    detailSlug: "blueberry",
    category: "photography",
    kind: "image",
    aspect: "9:16",
    className: "card-photo",
    typeLabel: "이미지",
    title: "보넬드 블루베리 뷰티컷",
    imageSrc: "/works/image/블루베리_섬네일.webp",
    imageAlt: "블루베리 뷰티컷 대표 이미지",
  },
  {
    id: "ssanghwa-beauty-cut",
    detailSlug: "ssanghwa",
    category: "photography",
    kind: "image",
    aspect: "9:16",
    className: "card-photo",
    typeLabel: "이미지",
    title: "홍동비책 쌍화진액 뷰티컷",
    imageSrc: "/works/image/쌍화진액_섬네일.webp",
    imageAlt: "쌍화진액 뷰티컷 대표 이미지",
  },
  {
    id: "suji-tang-beauty-cut",
    detailSlug: "suji-tang",
    category: "photography",
    kind: "image",
    aspect: "4:3",
    className: "card-photo",
    typeLabel: "이미지",
    title: "정성곳간 스지탕 뷰티컷",
    imageSrc: "/works/image/스지탕_섬네일.webp",
    imageAlt: "스지탕 뷰티컷 대표 이미지",
  },
  {
    id: "prune-noni-beauty-cut",
    detailSlug: "prune-noni",
    category: "photography",
    kind: "image",
    aspect: "4:3",
    className: "card-photo",
    typeLabel: "이미지",
    title: "보넬드 푸룬노니 뷰티컷",
    imageSrc: "/works/image/푸룬노니_섬네일.webp",
    imageAlt: "푸룬노니 뷰티컷 대표 이미지",
  },
  {
    id: "hanwoo-bulgogi-beauty-cut",
    detailSlug: "hanwoo-bulgogi",
    category: "photography",
    kind: "image",
    aspect: "4:3",
    className: "card-photo",
    typeLabel: "이미지",
    title: "정성곳간 한우뚝배기불고기 뷰티컷",
    imageSrc: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-01.webp",
    imageAlt: "한우뚝배기불고기 뷰티컷 대표 이미지",
  },
  {
    id: "black-goat-soup-beauty-cut",
    detailSlug: "black-goat-soup",
    category: "photography",
    kind: "image",
    aspect: "4:3",
    className: "card-photo",
    typeLabel: "이미지",
    title: "정성곳간 흑염소탕 뷰티컷",
    imageSrc: "/works/image/흑염소탕_섬네일.webp",
    imageAlt: "흑염소탕 뷰티컷 대표 이미지",
  },
  {
    id: "revv-fashion-brand-runway-film",
    category: "cinematography",
    kind: "video",
    aspect: "9:16",
    className: "card-video-tall",
    typeLabel: "영상",
    title: "REVV 패션 브랜드 런웨이 영상",
    videoSrc: "/works/video/revv-fashion-brand-runway-film.webm",
    href: "https://drive.google.com/file/d/1CEfCMNgE_wCD21QjkHORrru_x6eoNUjD/view?usp=sharing",
    ariaLabel: "REVV 패션 브랜드 런웨이 영상 열기",
  },
  {
    id: "sbs-special-docu-gunsan",
    category: "cinematography",
    kind: "video",
    aspect: "16:9",
    className: "card-video-inline",
    typeLabel: "영상",
    title: "SBS 일요특선 다큐 군산",
    videoSrc: "/works/video/sbs-special-docu-gunsan.webm",
    href: "https://drive.google.com/file/d/1miO7Bo0WzqpFldgH6BfqrA2l4tcz7LK2/view?usp=sharing",
    ariaLabel: "SBS 일요특선 다큐 군산 영상 열기",
  },
  {
    id: "tv-chosun-healthy-morning-haetteulnal",
    category: "cinematography",
    kind: "video",
    aspect: "16:9",
    className: "card-video-inline",
    typeLabel: "영상",
    title: "TV 조선 건강한 아침 해뜰날",
    videoSrc: "/works/video/tv-chosun-healthy-morning-haetteulnal.webm",
    href: "https://drive.google.com/file/d/1Avi2RgdaRjsX_j4ufzH_ESQUtvau2_T_/view?usp=sharing",
    ariaLabel: "TV 조선 건강한 아침 해뜰날 영상 열기",
  },
  {
    id: "naver-webtoon-jakdu-ai-teaser",
    category: "cinematography",
    kind: "video",
    aspect: "9:16",
    className: "card-video-tall",
    typeLabel: "영상",
    title: "네이버 웹툰 작두 AI 실사화 예고편",
    videoSrc: "/works/video/naver-webtoon-jakdu-ai-teaser.webm",
    href: "https://www.youtube.com/shorts/l52G3gsAczo",
    ariaLabel: "네이버 웹툰 작두 AI 실사화 예고편 영상 열기",
  },
  {
    id: "deardoor-cosmetics",
    category: "cinematography",
    kind: "video",
    aspect: "9:16",
    className: "card-video-tall",
    typeLabel: "영상",
    title: "디어도어 화장품",
    videoSrc: "/works/video/deardoor-cosmetics.webm",
    href: "https://drive.google.com/file/d/1ileHPTLmShEwWqvx19oXZcZfoJI9rdZC/view?usp=sharing",
    ariaLabel: "디어도어 화장품 영상 열기",
  },
  {
    id: "ridi-kill-me-love-me-shorts",
    category: "cinematography",
    kind: "video",
    aspect: "9:16",
    className: "card-video-tall",
    typeLabel: "영상",
    title: "리디 쇼츠 Kill Me Love Me",
    videoSrc: "/works/video/ridi-kill-me-love-me-shorts.webm",
    href: "https://drive.google.com/file/d/1fcPT_vWuZoZdiARZKSgxGkhdTTRzG6m0/view?usp=sharing",
    ariaLabel: "리디 쇼츠 Kill Me Love Me 영상 열기",
  },
  {
    id: "bitwoan-visual",
    detailSlug: "bitwoan",
    category: "photography",
    kind: "image",
    aspect: "4:3",
    className: "card-photo",
    typeLabel: "이미지",
    title: "비투앤 이미지",
    imageSrc: "/works/image/bitwoan-thumbnail.webp",
    imageAlt: "비투앤 대표 이미지",
  },
  {
    id: "anchangsal-beauty-cut",
    detailSlug: "anchangsal",
    category: "photography",
    kind: "image",
    aspect: "4:3",
    className: "card-photo",
    typeLabel: "이미지",
    title: "정성곳간 안창살 뷰티컷",
    imageSrc: "/works/image/anchangsal-thumbnail.webp",
    imageAlt: "정성곳간 안창살 뷰티컷 대표 이미지",
  },
  {
    id: "jeongseonggogan-kimchi-beauty-cut",
    detailSlug: "jeongseonggogan-kimchi",
    category: "photography",
    kind: "image",
    aspect: "4:3",
    className: "card-photo",
    typeLabel: "이미지",
    title: "정성곳간 김치 뷰티컷",
    imageSrc: "/works/image/jeongseonggogan-kimchi-thumbnail.webp",
    imageAlt: "정성곳간 김치 뷰티컷 대표 이미지",
  },
  {
    id: "haedamchon-gatkimchi-detail",
    detailSlug: "haedamchon-gatkimchi",
    category: "photography",
    kind: "image",
    aspect: "9:16",
    className: "card-photo",
    typeLabel: "이미지",
    title: "해담촌 갓김치 상세페이지",
    imageSrc: "/works/image/haedamchon-gatkimchi-thumbnail.webp",
    imageAlt: "해담촌 갓김치 상세페이지 대표 이미지",
  },
  {
    id: "sogalbijjim-detail",
    detailSlug: "sogalbijjim",
    category: "photography",
    kind: "image",
    aspect: "9:16",
    className: "card-photo",
    typeLabel: "이미지",
    title: "정성곳간 소갈비찜 상세페이지",
    imageSrc: "/works/image/sogalbijjim-thumbnail.webp",
    imageAlt: "정성곳간 소갈비찜 상세페이지 대표 이미지",
  },
  {
    id: "naver-webtoon-fantasy-training-camp-ai",
    category: "cinematography",
    kind: "video",
    aspect: "9:16",
    className: "card-video-tall",
    typeLabel: "영상",
    title: "네이버 웹툰 판타지 입소대 AI 실사화",
    videoSrc: "/works/video/naver-webtoon-fantasy-training-camp-ai.webm",
    href: "https://drive.google.com/file/d/1hdUOSu8KuTwNjHSniE4pqh5O33UdDovm/view?usp=sharing",
    ariaLabel: "네이버 웹툰 판타지 입소대 AI 실사화 영상 열기",
  },
  {
    id: "hongdong-ssanghwa-insert-ad",
    category: "cinematography",
    kind: "video",
    aspect: "16:9",
    className: "card-video-inline",
    typeLabel: "영상",
    title: "홍동비책 쌍화진액 인서트 광고",
    videoSrc: "/works/video/hongdong-ssanghwa-insert-ad.webm",
    href: "https://drive.google.com/file/d/1ZaSwpuo5_4uvKG-3SchUom1sK8Qy2cc3/view?usp=sharing",
    ariaLabel: "홍동비책 쌍화진액 인서트 광고 영상 열기",
  },
  {
    id: "jeongseonggogan-cheonggukjang-insert-ad",
    category: "cinematography",
    kind: "video",
    aspect: "16:9",
    className: "card-video-inline",
    typeLabel: "영상",
    title: "정성곳간 청국장 인서트 광고",
    videoSrc: "/works/video/jeongseonggogan-cheonggukjang-insert-ad.webm",
    href: "https://drive.google.com/file/d/1diOdePEhc5lG55wCwk1cVj0qr0kaD_BW/view?usp=sharing",
    ariaLabel: "정성곳간 청국장 인서트 광고 영상 열기",
  },
  {
    id: "jeongseonggogan-seafood-roe-soup-online-ad",
    category: "cinematography",
    kind: "video",
    aspect: "16:9",
    className: "card-video-inline",
    typeLabel: "영상",
    title: "정성곳간 해물알탕 온라인 광고",
    videoSrc: "/works/video/jeongseonggogan-seafood-roe-soup-online-ad.webm",
    href: "https://drive.google.com/file/d/1InHsddvAb_3ix9PVOaKCjXbsE0xl4z6y/view?usp=sharing",
    ariaLabel: "정성곳간 해물알탕 온라인 광고 영상 열기",
  },
  {
    id: "odd-youth-song-collab",
    category: "cinematography",
    kind: "video",
    aspect: "9:16",
    className: "card-video-tall",
    typeLabel: "영상",
    title: "오드유스 노래 협업",
    videoSrc: "/works/video/odd-youth-song-collab.webm",
    href: "https://www.youtube.com/shorts/N9_f-pN_HSs",
    ariaLabel: "오드유스 노래 협업 영상 열기",
  },
  {
    id: "granado-espada-m-ai-live-action",
    category: "cinematography",
    kind: "video",
    aspect: "9:16",
    className: "card-video-tall",
    typeLabel: "영상",
    title: "그라나도 에스파다M AI 실사화",
    videoSrc: "/works/video/granado-espada-m-ai-live-action.webm",
    href: "https://www.youtube.com/shorts/58UykbqUjsk",
    ariaLabel: "그라나도 에스파다M AI 실사화 영상 열기",
  },
  {
    id: "gyeongbuk-educators-ai-workshop",
    detailSlug: "gyeongbuk-educators-ai-workshop",
    category: "photography",
    kind: "image",
    aspect: "16:9",
    className: "card-photo",
    typeLabel: "이미지",
    title: "경북 교육자 대상 AI 역량강화 강의",
    imageSrc: "/works/image/gyeongbuk-educators-ai-workshop-thumbnail.webp",
    imageAlt: "경북 교육자 대상 AI 역량강화 강의 대표 이미지",
  },
  {
    id: "youngsan-ai-webtoon-lecture",
    detailSlug: "youngsan-ai-webtoon-lecture",
    category: "photography",
    kind: "image",
    aspect: "16:9",
    className: "card-photo",
    typeLabel: "이미지",
    title: "영산대 AI 웹툰 강의",
    imageSrc: "/works/image/youngsan-ai-webtoon-lecture-thumbnail.webp",
    imageAlt: "영산대 AI 웹툰 강의 대표 이미지",
  },
  {
    id: "rise-vfx-hackathon-ai-screening",
    detailSlug: "rise-vfx-hackathon-ai-screening",
    category: "photography",
    kind: "image",
    aspect: "9:16",
    className: "card-photo",
    typeLabel: "이미지",
    title: "RISE 사업특수효과(VFX) 해커톤 및 AI 상영",
    imageSrc: "/works/image/rise-vfx-hackathon-ai-screening-thumbnail.webp",
    imageAlt: "RISE 사업특수효과(VFX) 해커톤 및 AI 상영 대표 이미지",
  },
];

export const workDetails = [
  {
    slug: "revv",
    itemId: "revv-campaign-visual",
    eyebrow: "이미지 프로젝트",
    client: "올리비아로렌",
    brand: "REVV",
    title: "REVV 올리비아로렌 브랜드 런웨이",
    summary:
      "브랜드 런웨이 무드를 패션 비주얼 중심으로 정리한 프로젝트로, 룩의 존재감과 무대 인상을 동시에 보여주는 이미지를 구성했습니다.",
    overview: [
      "패션 실루엣과 조명 대비를 중심으로, 룩 자체의 인상이 먼저 전달되도록 장면을 정리했습니다.",
      "룩북, 캠페인 소개, 브랜드 아카이브에 바로 연결할 수 있도록 톤과 컷 구성을 통일감 있게 맞췄습니다.",
    ],
    credits: [
      ["Client", "올리비아로렌"],
      ["Brand", "REVV"],
      ["Format", "브랜드 런웨이 / 패션 비주얼"],
      ["Category", "이미지"],
    ],
    coverImage: "/works/projects/revv/revv-look-01.webp",
    coverAlt: "REVV 올리비아로렌 브랜드 런웨이 대표 컷",
    gallery: [
      { src: "/works/projects/revv/revv-look-01.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 1" },
      { src: "/works/projects/revv/revv-look-02.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 2" },
      { src: "/works/projects/revv/revv-look-03.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 3" },
      { src: "/works/projects/revv/revv-look-04.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 4" },
      { src: "/works/projects/revv/revv-look-05.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 5" },
      { src: "/works/projects/revv/revv-look-06.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 6" },
      { src: "/works/projects/revv/revv-look-07.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 7" },
      { src: "/works/projects/revv/revv-look-08.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 8" },
      { src: "/works/projects/revv/revv-look-09.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 9" },
      { src: "/works/projects/revv/revv-look-10.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 10" },
      { src: "/works/projects/revv/revv-look-11.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 11" },
      { src: "/works/projects/revv/revv-look-12.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 12" },
    ],
  },
  {
    slug: "saerom-black-goat-beauty-cut",
    itemId: "saerom-herbal-beauty-cut",
    eyebrow: "이미지 프로젝트",
    client: "행복을 파는 사람들",
    brand: "새롬한방 흑염소진액",
    title: "새롬한방 흑염소진액 뷰티컷",
    summary:
      "전통 한방 원료의 밀도와 제품의 프리미엄 무드를 동시에 보여주기 위해, 재료의 질감과 패키지의 존재감을 중심으로 정리한 비주얼 시리즈입니다.",
    overview: [
      "제품이 단순히 놓여 있는 느낌보다, 흑염소진액이 가진 진중한 인상과 원료의 무게감이 함께 전달되도록 장면을 구성했습니다.",
      "검은 패키지와 한방 재료의 대비를 살리면서, 상세페이지나 판매 채널에서 바로 사용할 수 있는 실무형 컷으로 연결하는 데 집중했습니다.",
    ],
    credits: [
      ["Client", "행복을 파는 사람들"],
      ["Brand", "새롬한방"],
      ["Format", "상세페이지 / 광고용 비주얼"],
      ["Category", "이미지"],
    ],
    coverImage: "/works/projects/saerom/saerom-cut-01.webp",
    coverAlt: "새롬한방 흑염소진액 대표 컷",
    gallery: [
      { src: "/works/projects/saerom/saerom-cut-01.webp", alt: "새롬한방 흑염소진액 뷰티컷 1" },
      { src: "/works/projects/saerom/saerom-cut-02.webp", alt: "새롬한방 흑염소진액 뷰티컷 2" },
      { src: "/works/projects/saerom/saerom-cut-03.webp", alt: "새롬한방 흑염소진액 뷰티컷 3" },
      { src: "/works/projects/saerom/saerom-cut-04.webp", alt: "새롬한방 흑염소진액 뷰티컷 4" },
      { src: "/works/projects/saerom/saerom-cut-05.webp", alt: "새롬한방 흑염소진액 뷰티컷 5" },
      { src: "/works/projects/saerom/saerom-cut-06.webp", alt: "새롬한방 흑염소진액 뷰티컷 6" },
      { src: "/works/projects/saerom/saerom-cut-07.webp", alt: "새롬한방 흑염소진액 뷰티컷 7" },
      { src: "/works/projects/saerom/saerom-cut-08.webp", alt: "새롬한방 흑염소진액 뷰티컷 8" },
      { src: "/works/projects/saerom/saerom-cut-09.webp", alt: "새롬한방 흑염소진액 뷰티컷 9" },
      { src: "/works/projects/saerom/saerom-cut-10.webp", alt: "새롬한방 흑염소진액 뷰티컷 10" },
    ],
  },
  {
    slug: "richcoco",
    itemId: "richcoco-beauty-cut",
    eyebrow: "이미지 프로젝트",
    client: "행복을 파는 사람들",
    brand: "리치코코",
    title: "보넬드 리치코코 뷰티컷",
    summary: "리치코코 제품의 컬러감과 패키지 무드를 중심으로 정리한 비주얼 시리즈입니다.",
    overview: [
      "제품의 톤과 디저트 무드를 함께 살리면서, 상세페이지와 광고 비주얼에 바로 연결할 수 있는 컷 위주로 구성했습니다.",
      "브랜드의 밝은 인상을 유지하면서도 제품 정보 전달에 방해되지 않도록 배경과 오브젝트 밀도를 정리했습니다.",
    ],
    credits: [
      ["Client", "행복을 파는 사람들"],
      ["Brand", "리치코코"],
      ["Format", "상세페이지 / 광고용 비주얼"],
      ["Category", "이미지"],
    ],
    coverImage: "/works/projects/richcoco/richcoco-01.webp",
    coverAlt: "리치코코 대표 컷",
    gallery: [
      { src: "/works/projects/richcoco/richcoco-01.webp", alt: "리치코코 뷰티컷 1" },
      { src: "/works/projects/richcoco/richcoco-02.webp", alt: "리치코코 뷰티컷 2" },
      { src: "/works/projects/richcoco/richcoco-03.webp", alt: "리치코코 뷰티컷 3" },
      { src: "/works/projects/richcoco/richcoco-04.webp", alt: "리치코코 뷰티컷 4" },
      { src: "/works/projects/richcoco/richcoco-05.webp", alt: "리치코코 뷰티컷 5" },
      { src: "/works/projects/richcoco/richcoco-06.webp", alt: "리치코코 뷰티컷 6" },
      { src: "/works/projects/richcoco/richcoco-07.webp", alt: "리치코코 뷰티컷 7" },
      { src: "/works/projects/richcoco/richcoco-08.webp", alt: "리치코코 뷰티컷 8" },
      { src: "/works/projects/richcoco/richcoco-09.webp", alt: "리치코코 뷰티컷 9" },
      { src: "/works/projects/richcoco/richcoco-10.webp", alt: "리치코코 뷰티컷 10" },
      { src: "/works/projects/richcoco/richcoco-11.webp", alt: "리치코코 뷰티컷 11" },
      { src: "/works/projects/richcoco/richcoco-12.webp", alt: "리치코코 뷰티컷 12" },
      { src: "/works/projects/richcoco/richcoco-13.webp", alt: "리치코코 뷰티컷 13" },
      { src: "/works/projects/richcoco/richcoco-14.webp", alt: "리치코코 뷰티컷 14" },
    ],
  },
  {
    slug: "galbitsal",
    itemId: "galbitsal-beauty-cut",
    eyebrow: "이미지 프로젝트",
    client: "행복을 파는 사람들",
    brand: "갈빗살",
    title: "정성곳간 갈빗살 뷰티컷",
    summary: "갈빗살 제품의 식감과 조리 인상을 강하게 보여주기 위해 정리한 상세용 비주얼 시리즈입니다.",
    overview: [
      "완성 컷과 원육 컷을 함께 묶어, 제품의 풍성한 인상과 원재료의 신뢰감을 동시에 전달하도록 구성했습니다.",
      "광고, 판매 페이지, 배너 영역에서 그대로 활용할 수 있도록 컷 간 톤과 밀도를 일정하게 맞췄습니다.",
    ],
    credits: [
      ["Client", "행복을 파는 사람들"],
      ["Brand", "갈빗살"],
      ["Format", "상세페이지 / 광고용 비주얼"],
      ["Category", "이미지"],
    ],
    coverImage: "/works/projects/galbitsal/galbitsal-01.webp",
    coverAlt: "갈빗살 대표 컷",
    gallery: [
      { src: "/works/projects/galbitsal/galbitsal-01.webp", alt: "갈빗살 뷰티컷 1" },
      { src: "/works/projects/galbitsal/galbitsal-02.webp", alt: "갈빗살 뷰티컷 2" },
      { src: "/works/projects/galbitsal/galbitsal-03.webp", alt: "갈빗살 뷰티컷 3" },
      { src: "/works/projects/galbitsal/galbitsal-04.webp", alt: "갈빗살 뷰티컷 4" },
      { src: "/works/projects/galbitsal/galbitsal-05.webp", alt: "갈빗살 뷰티컷 5" },
      { src: "/works/projects/galbitsal/galbitsal-06.webp", alt: "갈빗살 뷰티컷 6" },
      { src: "/works/projects/galbitsal/galbitsal-07.webp", alt: "갈빗살 뷰티컷 7" },
      { src: "/works/projects/galbitsal/galbitsal-08.webp", alt: "갈빗살 뷰티컷 8" },
      { src: "/works/projects/galbitsal/galbitsal-09.webp", alt: "갈빗살 뷰티컷 9" },
      { src: "/works/projects/galbitsal/galbitsal-10.webp", alt: "갈빗살 뷰티컷 10" },
      { src: "/works/projects/galbitsal/galbitsal-11.webp", alt: "갈빗살 뷰티컷 11" },
      { src: "/works/projects/galbitsal/galbitsal-12.webp", alt: "갈빗살 뷰티컷 12" },
      { src: "/works/projects/galbitsal/galbitsal-13.webp", alt: "갈빗살 뷰티컷 13" },
      { src: "/works/projects/galbitsal/galbitsal-14.webp", alt: "갈빗살 뷰티컷 14" },
      { src: "/works/projects/galbitsal/galbitsal-15.webp", alt: "갈빗살 뷰티컷 15" },
      { src: "/works/projects/galbitsal/galbitsal-16.webp", alt: "갈빗살 뷰티컷 16" },
      { src: "/works/projects/galbitsal/galbitsal-17.webp", alt: "갈빗살 뷰티컷 17" },
      { src: "/works/projects/galbitsal/galbitsal-18.webp", alt: "갈빗살 뷰티컷 18" },
      { src: "/works/projects/galbitsal/galbitsal-19.webp", alt: "갈빗살 뷰티컷 19" },
      { src: "/works/projects/galbitsal/galbitsal-20.webp", alt: "갈빗살 뷰티컷 20" },
    ],
  },
  {
    slug: "blueberry",
    itemId: "blueberry-beauty-cut",
    eyebrow: "이미지 프로젝트",
    client: "행복을 파는 사람들",
    brand: "블루베리",
    title: "보넬드 블루베리 뷰티컷",
    summary: "블루베리 제품의 산뜻한 컬러와 음용 이미지를 강조해 정리한 비주얼 시리즈입니다.",
    overview: [
      "제품 컬러와 원재료 무드가 동시에 살아나도록 블루 계열의 인상을 중심으로 컷을 구성했습니다.",
      "모바일 상세페이지나 세로형 광고에도 바로 적용할 수 있도록 세로 컷 흐름을 유지했습니다.",
    ],
    credits: [
      ["Client", "행복을 파는 사람들"],
      ["Brand", "블루베리"],
      ["Format", "상세페이지 / 광고용 비주얼"],
      ["Category", "이미지"],
    ],
    coverImage: "/works/projects/blueberry/blueberry-01.webp",
    coverAlt: "블루베리 대표 컷",
    gallery: [
      { src: "/works/projects/blueberry/blueberry-01.webp", alt: "블루베리 뷰티컷 1" },
      { src: "/works/projects/blueberry/blueberry-02.webp", alt: "블루베리 뷰티컷 2" },
      { src: "/works/projects/blueberry/blueberry-03.webp", alt: "블루베리 뷰티컷 3" },
      { src: "/works/projects/blueberry/blueberry-04.webp", alt: "블루베리 뷰티컷 4" },
      { src: "/works/projects/blueberry/blueberry-05.webp", alt: "블루베리 뷰티컷 5" },
      { src: "/works/projects/blueberry/blueberry-06.webp", alt: "블루베리 뷰티컷 6" },
      { src: "/works/projects/blueberry/blueberry-07.webp", alt: "블루베리 뷰티컷 7" },
      { src: "/works/projects/blueberry/blueberry-08.webp", alt: "블루베리 뷰티컷 8" },
      { src: "/works/projects/blueberry/blueberry-09.webp", alt: "블루베리 뷰티컷 9" },
    ],
  },
  {
    slug: "ssanghwa",
    itemId: "ssanghwa-beauty-cut",
    eyebrow: "이미지 프로젝트",
    client: "행복을 파는 사람들",
    brand: "쌍화진액",
    title: "홍동비책 쌍화진액 뷰티컷",
    summary: "쌍화진액 제품의 농도감과 프리미엄 인상을 중심으로 정리한 뷰티컷 시리즈입니다.",
    overview: [
      "누끼컷과 상세 이미지가 아닌 뷰티컷만 선별해, 제품이 가장 설득력 있게 보이는 장면 위주로 구성했습니다.",
      "전통 한방 무드와 현대적인 상품 비주얼 사이 균형을 맞추는 데 집중했습니다.",
    ],
    credits: [
      ["Client", "행복을 파는 사람들"],
      ["Brand", "쌍화진액"],
      ["Format", "상세페이지 / 광고용 비주얼"],
      ["Category", "이미지"],
    ],
    coverImage: "/works/projects/ssanghwa/ssanghwa-01.webp",
    coverAlt: "쌍화진액 대표 컷",
    gallery: [
      { src: "/works/projects/ssanghwa/ssanghwa-01.webp", alt: "쌍화진액 뷰티컷 1" },
      { src: "/works/projects/ssanghwa/ssanghwa-02.webp", alt: "쌍화진액 뷰티컷 2" },
      { src: "/works/projects/ssanghwa/ssanghwa-03.webp", alt: "쌍화진액 뷰티컷 3" },
      { src: "/works/projects/ssanghwa/ssanghwa-04.webp", alt: "쌍화진액 뷰티컷 4" },
      { src: "/works/projects/ssanghwa/ssanghwa-05.webp", alt: "쌍화진액 뷰티컷 5" },
      { src: "/works/projects/ssanghwa/ssanghwa-06.webp", alt: "쌍화진액 뷰티컷 6" },
      { src: "/works/projects/ssanghwa/ssanghwa-07.webp", alt: "쌍화진액 뷰티컷 7" },
      { src: "/works/projects/ssanghwa/ssanghwa-08.webp", alt: "쌍화진액 뷰티컷 8" },
      { src: "/works/projects/ssanghwa/ssanghwa-09.webp", alt: "쌍화진액 뷰티컷 9" },
      { src: "/works/projects/ssanghwa/ssanghwa-10.webp", alt: "쌍화진액 뷰티컷 10" },
    ],
  },
  {
    slug: "suji-tang",
    itemId: "suji-tang-beauty-cut",
    eyebrow: "이미지 프로젝트",
    client: "행복을 파는 사람들",
    brand: "스지탕",
    title: "정성곳간 스지탕 뷰티컷",
    summary: "스지탕의 온기와 재료감을 중심으로 구성한 푸드 비주얼 시리즈입니다.",
    overview: [
      "누끼컷은 제외하고 완성된 장면 중심의 뷰티컷만 선별해, 제품 사용처에서 바로 활용하기 쉬운 흐름으로 정리했습니다.",
      "국물의 깊이감과 재료의 존재감이 자연스럽게 전달되도록 색과 대비를 맞췄습니다.",
    ],
    credits: [
      ["Client", "행복을 파는 사람들"],
      ["Brand", "스지탕"],
      ["Format", "상세페이지 / 광고용 비주얼"],
      ["Category", "이미지"],
    ],
    coverImage: "/works/projects/suji-tang/suji-tang-01.webp",
    coverAlt: "스지탕 대표 컷",
    gallery: [
      { src: "/works/projects/suji-tang/suji-tang-01.webp", alt: "스지탕 뷰티컷 1" },
      { src: "/works/projects/suji-tang/suji-tang-02.webp", alt: "스지탕 뷰티컷 2" },
      { src: "/works/projects/suji-tang/suji-tang-03.webp", alt: "스지탕 뷰티컷 3" },
      { src: "/works/projects/suji-tang/suji-tang-04.webp", alt: "스지탕 뷰티컷 4" },
      { src: "/works/projects/suji-tang/suji-tang-05.webp", alt: "스지탕 뷰티컷 5" },
      { src: "/works/projects/suji-tang/suji-tang-06.webp", alt: "스지탕 뷰티컷 6" },
      { src: "/works/projects/suji-tang/suji-tang-07.webp", alt: "스지탕 뷰티컷 7" },
      { src: "/works/projects/suji-tang/suji-tang-08.webp", alt: "스지탕 뷰티컷 8" },
      { src: "/works/projects/suji-tang/suji-tang-09.webp", alt: "스지탕 뷰티컷 9" },
      { src: "/works/projects/suji-tang/suji-tang-10.webp", alt: "스지탕 뷰티컷 10" },
      { src: "/works/projects/suji-tang/suji-tang-11.webp", alt: "스지탕 뷰티컷 11" },
    ],
  },
  {
    slug: "prune-noni",
    itemId: "prune-noni-beauty-cut",
    eyebrow: "이미지 프로젝트",
    client: "행복을 파는 사람들",
    brand: "푸룬노니",
    title: "보넬드 푸룬노니 뷰티컷",
    summary: "푸룬노니 제품의 건강한 무드와 컬러 인상을 중심으로 정리한 비주얼 시리즈입니다.",
    overview: [
      "과일 원료와 제품 패키지가 함께 살아나도록 무드를 맞추고, 상품 판매 페이지에 바로 적용 가능한 장면 위주로 구성했습니다.",
      "움직이는 컷이 아닌 정적인 뷰티컷만 선별해 프로젝트 흐름을 단순하게 정리했습니다.",
    ],
    credits: [
      ["Client", "행복을 파는 사람들"],
      ["Brand", "푸룬노니"],
      ["Format", "상세페이지 / 광고용 비주얼"],
      ["Category", "이미지"],
    ],
    coverImage: "/works/projects/prune-noni/prune-noni-01.webp",
    coverAlt: "푸룬노니 대표 컷",
    gallery: [
      { src: "/works/projects/prune-noni/prune-noni-01.webp", alt: "푸룬노니 뷰티컷 1" },
      { src: "/works/projects/prune-noni/prune-noni-02.webp", alt: "푸룬노니 뷰티컷 2" },
      { src: "/works/projects/prune-noni/prune-noni-03.webp", alt: "푸룬노니 뷰티컷 3" },
      { src: "/works/projects/prune-noni/prune-noni-04.webp", alt: "푸룬노니 뷰티컷 4" },
      { src: "/works/projects/prune-noni/prune-noni-05.webp", alt: "푸룬노니 뷰티컷 5" },
      { src: "/works/projects/prune-noni/prune-noni-06.webp", alt: "푸룬노니 뷰티컷 6" },
      { src: "/works/projects/prune-noni/prune-noni-07.webp", alt: "푸룬노니 뷰티컷 7" },
      { src: "/works/projects/prune-noni/prune-noni-08.webp", alt: "푸룬노니 뷰티컷 8" },
      { src: "/works/projects/prune-noni/prune-noni-09.webp", alt: "푸룬노니 뷰티컷 9" },
    ],
  },
  {
    slug: "hanwoo-bulgogi",
    itemId: "hanwoo-bulgogi-beauty-cut",
    eyebrow: "이미지 프로젝트",
    client: "행복을 파는 사람들",
    brand: "한우뚝배기불고기",
    title: "정성곳간 한우뚝배기불고기 뷰티컷",
    summary: "한우뚝배기불고기 제품의 푸드 임팩트와 완성 컷 무드를 중심으로 구성한 프로젝트입니다.",
    overview: [
      "완성 음식의 풍부한 인상이 먼저 전달되도록 장면을 정리하고, 판매용 페이지에 바로 연결 가능한 컷 흐름으로 구성했습니다.",
      "누끼컷은 제외하고 푸드 연출이 살아 있는 뷰티컷만 사용해 프로젝트 성격을 분명하게 정리했습니다.",
    ],
    credits: [
      ["Client", "행복을 파는 사람들"],
      ["Brand", "한우뚝배기불고기"],
      ["Format", "상세페이지 / 광고용 비주얼"],
      ["Category", "이미지"],
    ],
    coverImage: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-01.webp",
    coverAlt: "한우뚝배기불고기 대표 컷",
    gallery: [
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-01.webp", alt: "한우뚝배기불고기 뷰티컷 1" },
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-02.webp", alt: "한우뚝배기불고기 뷰티컷 2" },
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-03.webp", alt: "한우뚝배기불고기 뷰티컷 3" },
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-04.webp", alt: "한우뚝배기불고기 뷰티컷 4" },
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-05.webp", alt: "한우뚝배기불고기 뷰티컷 5" },
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-06.webp", alt: "한우뚝배기불고기 뷰티컷 6" },
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-07.webp", alt: "한우뚝배기불고기 뷰티컷 7" },
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-08.webp", alt: "한우뚝배기불고기 뷰티컷 8" },
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-09.webp", alt: "한우뚝배기불고기 뷰티컷 9" },
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-10.webp", alt: "한우뚝배기불고기 뷰티컷 10" },
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-11.webp", alt: "한우뚝배기불고기 뷰티컷 11" },
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-12.webp", alt: "한우뚝배기불고기 뷰티컷 12" },
    ],
  },
  {
    slug: "black-goat-soup",
    itemId: "black-goat-soup-beauty-cut",
    eyebrow: "이미지 프로젝트",
    client: "행복을 파는 사람들",
    brand: "흑염소탕",
    title: "정성곳간 흑염소탕 뷰티컷",
    summary: "흑염소탕 제품의 묵직한 인상과 국물의 깊이를 살려 구성한 비주얼 시리즈입니다.",
    overview: [
      "누끼컷은 제외하고 실제 사용 장면에 가까운 뷰티컷만 선별해 프로젝트 흐름을 정리했습니다.",
      "한방 보양식의 무게감이 자연스럽게 전달되도록 어두운 톤과 재료감을 중심으로 컷을 구성했습니다.",
    ],
    credits: [
      ["Client", "행복을 파는 사람들"],
      ["Brand", "흑염소탕"],
      ["Format", "상세페이지 / 광고용 비주얼"],
      ["Category", "이미지"],
    ],
    coverImage: "/works/projects/black-goat-soup/black-goat-soup-01.webp",
    coverAlt: "흑염소탕 대표 컷",
    gallery: [
      { src: "/works/projects/black-goat-soup/black-goat-soup-01.webp", alt: "흑염소탕 뷰티컷 1" },
      { src: "/works/projects/black-goat-soup/black-goat-soup-02.webp", alt: "흑염소탕 뷰티컷 2" },
      { src: "/works/projects/black-goat-soup/black-goat-soup-03.webp", alt: "흑염소탕 뷰티컷 3" },
      { src: "/works/projects/black-goat-soup/black-goat-soup-04.webp", alt: "흑염소탕 뷰티컷 4" },
      { src: "/works/projects/black-goat-soup/black-goat-soup-05.webp", alt: "흑염소탕 뷰티컷 5" },
      { src: "/works/projects/black-goat-soup/black-goat-soup-06.webp", alt: "흑염소탕 뷰티컷 6" },
      { src: "/works/projects/black-goat-soup/black-goat-soup-07.webp", alt: "흑염소탕 뷰티컷 7" },
      { src: "/works/projects/black-goat-soup/black-goat-soup-08.webp", alt: "흑염소탕 뷰티컷 8" },
      { src: "/works/projects/black-goat-soup/black-goat-soup-09.webp", alt: "흑염소탕 뷰티컷 9" },
      { src: "/works/projects/black-goat-soup/black-goat-soup-10.webp", alt: "흑염소탕 뷰티컷 10" },
    ],
  },
  {
    slug: "bitwoan",
    itemId: "bitwoan-visual",
    eyebrow: "이미지 프로젝트",
    client: "비투앤",
    brand: "비투앤",
    title: "비투앤 이미지",
    summary: "비투앤의 브랜드 인상과 제품 이미지를 함께 보여주기 위해 정리한 비주얼 프로젝트입니다.",
    overview: [
      "브랜드 무드와 상품 인상이 분리되지 않도록 컷 간 톤과 배치를 정리했습니다.",
      "소개 자료, 제안서, 홍보물에서 바로 활용할 수 있도록 간결한 흐름으로 이미지를 구성했습니다.",
    ],
    credits: [
      ["Client", "비투앤"],
      ["Brand", "비투앤"],
      ["Format", "브랜드 비주얼 / 이미지"],
      ["Category", "이미지"],
    ],
    coverImage: "/works/projects/bitwoan/bitwoan-01.webp",
    coverAlt: "비투앤 대표 이미지",
    gallery: [
      { src: "/works/projects/bitwoan/bitwoan-01.webp", alt: "비투앤 이미지 1" },
      { src: "/works/projects/bitwoan/bitwoan-02.webp", alt: "비투앤 이미지 2" },
      { src: "/works/projects/bitwoan/bitwoan-03.webp", alt: "비투앤 이미지 3" },
      { src: "/works/projects/bitwoan/bitwoan-04.webp", alt: "비투앤 이미지 4" },
      { src: "/works/projects/bitwoan/bitwoan-05.webp", alt: "비투앤 이미지 5" },
    ],
  },
  {
    slug: "anchangsal",
    itemId: "anchangsal-beauty-cut",
    eyebrow: "이미지 프로젝트",
    client: "행복을 파는 사람들",
    brand: "정성곳간 안창살",
    title: "정성곳간 안창살 뷰티컷",
    summary: "안창살 제품의 식감과 원육 인상을 함께 보여주기 위해 구성한 푸드 비주얼 시리즈입니다.",
    overview: [
      "완성 컷과 원육 컷을 함께 배치해 제품의 풍성한 인상과 재료의 신뢰감을 동시에 전달하도록 정리했습니다.",
      "상세페이지와 판매 콘텐츠에서 바로 활용할 수 있도록 컷 간 색감과 밀도를 일정하게 맞췄습니다.",
    ],
    credits: [
      ["Client", "행복을 파는 사람들"],
      ["Brand", "정성곳간 안창살"],
      ["Format", "상세페이지 / 광고용 비주얼"],
      ["Category", "이미지"],
    ],
    coverImage: "/works/projects/anchangsal/anchangsal-01.webp",
    coverAlt: "정성곳간 안창살 뷰티컷 대표 이미지",
    gallery: [
      { src: "/works/projects/anchangsal/anchangsal-01.webp", alt: "정성곳간 안창살 뷰티컷 1" },
      { src: "/works/projects/anchangsal/anchangsal-02.webp", alt: "정성곳간 안창살 뷰티컷 2" },
      { src: "/works/projects/anchangsal/anchangsal-03.webp", alt: "정성곳간 안창살 뷰티컷 3" },
      { src: "/works/projects/anchangsal/anchangsal-04.webp", alt: "정성곳간 안창살 뷰티컷 4" },
      { src: "/works/projects/anchangsal/anchangsal-05.webp", alt: "정성곳간 안창살 뷰티컷 5" },
      { src: "/works/projects/anchangsal/anchangsal-06.webp", alt: "정성곳간 안창살 뷰티컷 6" },
      { src: "/works/projects/anchangsal/anchangsal-07.webp", alt: "정성곳간 안창살 뷰티컷 7" },
      { src: "/works/projects/anchangsal/anchangsal-08.webp", alt: "정성곳간 안창살 뷰티컷 8" },
      { src: "/works/projects/anchangsal/anchangsal-09.webp", alt: "정성곳간 안창살 뷰티컷 9" },
      { src: "/works/projects/anchangsal/anchangsal-10.webp", alt: "정성곳간 안창살 뷰티컷 10" },
      { src: "/works/projects/anchangsal/anchangsal-11.webp", alt: "정성곳간 안창살 뷰티컷 11" },
      { src: "/works/projects/anchangsal/anchangsal-12.webp", alt: "정성곳간 안창살 뷰티컷 12" },
      { src: "/works/projects/anchangsal/anchangsal-13.webp", alt: "정성곳간 안창살 뷰티컷 13" },
      { src: "/works/projects/anchangsal/anchangsal-14.webp", alt: "정성곳간 안창살 뷰티컷 14" },
      { src: "/works/projects/anchangsal/anchangsal-15.webp", alt: "정성곳간 안창살 뷰티컷 15" },
      { src: "/works/projects/anchangsal/anchangsal-16.webp", alt: "정성곳간 안창살 뷰티컷 16" },
      { src: "/works/projects/anchangsal/anchangsal-17.webp", alt: "정성곳간 안창살 뷰티컷 17" },
      { src: "/works/projects/anchangsal/anchangsal-18.webp", alt: "정성곳간 안창살 뷰티컷 18" },
      { src: "/works/projects/anchangsal/anchangsal-19.webp", alt: "정성곳간 안창살 뷰티컷 19" },
      { src: "/works/projects/anchangsal/anchangsal-20.webp", alt: "정성곳간 안창살 뷰티컷 20" },
    ],
  },
  {
    slug: "jeongseonggogan-kimchi",
    itemId: "jeongseonggogan-kimchi-beauty-cut",
    eyebrow: "이미지 프로젝트",
    client: "행복을 파는 사람들",
    brand: "정성곳간 김치",
    title: "정성곳간 김치 뷰티컷",
    summary: "정성곳간 김치 라인의 컬러감과 재료 인상을 중심으로 정리한 푸드 비주얼 프로젝트입니다.",
    overview: [
      "다양한 김치 라인의 개성이 흐트러지지 않도록 전체 톤을 맞추고, 컷별 식재료 인상은 분명하게 살렸습니다.",
      "상세페이지, 배너, 상품 소개 영역에 바로 활용할 수 있도록 구도와 배경 밀도를 안정적으로 정리했습니다.",
    ],
    credits: [
      ["Client", "행복을 파는 사람들"],
      ["Brand", "정성곳간 김치"],
      ["Format", "상세페이지 / 광고용 비주얼"],
      ["Category", "이미지"],
    ],
    coverImage: "/works/projects/jeongseonggogan-kimchi/jeongseonggogan-kimchi-01.webp",
    coverAlt: "정성곳간 김치 뷰티컷 대표 이미지",
    gallery: [
      { src: "/works/projects/jeongseonggogan-kimchi/jeongseonggogan-kimchi-01.webp", alt: "정성곳간 김치 뷰티컷 1" },
      { src: "/works/projects/jeongseonggogan-kimchi/jeongseonggogan-kimchi-02.webp", alt: "정성곳간 김치 뷰티컷 2" },
      { src: "/works/projects/jeongseonggogan-kimchi/jeongseonggogan-kimchi-03.webp", alt: "정성곳간 김치 뷰티컷 3" },
      { src: "/works/projects/jeongseonggogan-kimchi/jeongseonggogan-kimchi-04.webp", alt: "정성곳간 김치 뷰티컷 4" },
      { src: "/works/projects/jeongseonggogan-kimchi/jeongseonggogan-kimchi-05.webp", alt: "정성곳간 김치 뷰티컷 5" },
      { src: "/works/projects/jeongseonggogan-kimchi/jeongseonggogan-kimchi-06.webp", alt: "정성곳간 김치 뷰티컷 6" },
      { src: "/works/projects/jeongseonggogan-kimchi/jeongseonggogan-kimchi-07.webp", alt: "정성곳간 김치 뷰티컷 7" },
      { src: "/works/projects/jeongseonggogan-kimchi/jeongseonggogan-kimchi-08.webp", alt: "정성곳간 김치 뷰티컷 8" },
      { src: "/works/projects/jeongseonggogan-kimchi/jeongseonggogan-kimchi-09.webp", alt: "정성곳간 김치 뷰티컷 9" },
      { src: "/works/projects/jeongseonggogan-kimchi/jeongseonggogan-kimchi-10.webp", alt: "정성곳간 김치 뷰티컷 10" },
      { src: "/works/projects/jeongseonggogan-kimchi/jeongseonggogan-kimchi-11.webp", alt: "정성곳간 김치 뷰티컷 11" },
      { src: "/works/projects/jeongseonggogan-kimchi/jeongseonggogan-kimchi-12.webp", alt: "정성곳간 김치 뷰티컷 12" },
      { src: "/works/projects/jeongseonggogan-kimchi/jeongseonggogan-kimchi-13.webp", alt: "정성곳간 김치 뷰티컷 13" },
      { src: "/works/projects/jeongseonggogan-kimchi/jeongseonggogan-kimchi-14.webp", alt: "정성곳간 김치 뷰티컷 14" },
      { src: "/works/projects/jeongseonggogan-kimchi/jeongseonggogan-kimchi-15.webp", alt: "정성곳간 김치 뷰티컷 15" },
    ],
  },
  {
    slug: "premium-bachelor-kimchi",
    itemId: "premium-bachelor-kimchi-detail",
    eyebrow: "이미지 프로젝트",
    client: "행복을 파는 사람들",
    brand: "정성곳간 프리미엄 총각김치",
    title: "정성곳간 프리미엄 총각김치 상세페이지",
    summary:
      "정성곳간 프리미엄 총각김치의 제품 특성과 식재료 인상을 길게 전달할 수 있도록 세로형 상세페이지 흐름으로 정리한 프로젝트입니다.",
    overview: [
      "제품 특징, 구성 정보, 푸드 비주얼이 단절되지 않도록 한 화면 안에서 자연스럽게 이어지는 순서로 이미지를 정리했습니다.",
      "실제 판매 페이지에 바로 적용할 수 있도록 긴 세로 흐름과 정보성 컷의 밀도를 안정적으로 맞췄습니다.",
    ],
    credits: [
      ["Client", "행복을 파는 사람들"],
      ["Brand", "정성곳간 프리미엄 총각김치"],
      ["Format", "상세페이지 / 브랜드 비주얼"],
      ["Category", "이미지"],
    ],
    coverImage: "/works/projects/premium-bachelor-kimchi/premium-bachelor-kimchi-01.webp",
    coverAlt: "정성곳간 프리미엄 총각김치 상세페이지 대표 이미지",
    gallery: [
      { src: "/works/projects/premium-bachelor-kimchi/premium-bachelor-kimchi-01.webp", alt: "정성곳간 프리미엄 총각김치 상세페이지 1" },
      { src: "/works/projects/premium-bachelor-kimchi/premium-bachelor-kimchi-02.webp", alt: "정성곳간 프리미엄 총각김치 상세페이지 2" },
      { src: "/works/projects/premium-bachelor-kimchi/premium-bachelor-kimchi-03.webp", alt: "정성곳간 프리미엄 총각김치 상세페이지 3" },
      { src: "/works/projects/premium-bachelor-kimchi/premium-bachelor-kimchi-04.webp", alt: "정성곳간 프리미엄 총각김치 상세페이지 4" },
      { src: "/works/projects/premium-bachelor-kimchi/premium-bachelor-kimchi-05.webp", alt: "정성곳간 프리미엄 총각김치 상세페이지 5" },
      { src: "/works/projects/premium-bachelor-kimchi/premium-bachelor-kimchi-06.webp", alt: "정성곳간 프리미엄 총각김치 상세페이지 6" },
      { src: "/works/projects/premium-bachelor-kimchi/premium-bachelor-kimchi-07.webp", alt: "정성곳간 프리미엄 총각김치 상세페이지 7" },
      { src: "/works/projects/premium-bachelor-kimchi/premium-bachelor-kimchi-08.webp", alt: "정성곳간 프리미엄 총각김치 상세페이지 8" },
      { src: "/works/projects/premium-bachelor-kimchi/premium-bachelor-kimchi-09.webp", alt: "정성곳간 프리미엄 총각김치 상세페이지 9" },
      { src: "/works/projects/premium-bachelor-kimchi/premium-bachelor-kimchi-10.webp", alt: "정성곳간 프리미엄 총각김치 상세페이지 10" },
      { src: "/works/projects/premium-bachelor-kimchi/premium-bachelor-kimchi-11.webp", alt: "정성곳간 프리미엄 총각김치 상세페이지 11" },
      { src: "/works/projects/premium-bachelor-kimchi/premium-bachelor-kimchi-12.webp", alt: "정성곳간 프리미엄 총각김치 상세페이지 12" },
      { src: "/works/projects/premium-bachelor-kimchi/premium-bachelor-kimchi-13.webp", alt: "정성곳간 프리미엄 총각김치 상세페이지 13" },
      { src: "/works/projects/premium-bachelor-kimchi/premium-bachelor-kimchi-14.webp", alt: "정성곳간 프리미엄 총각김치 상세페이지 14" },
    ],
  },
  {
    slug: "lefleur-oral-spray",
    itemId: "lefleur-oral-spray-detail",
    eyebrow: "이미지 프로젝트",
    client: "르플레르",
    brand: "르플레르 구강 스프레이",
    title: "르플레르 구강 스프레이 상세페이지",
    summary:
      "르플레르 구강 스프레이의 제품 무드와 사용 장면, 정보성 화면을 함께 전달할 수 있도록 구성한 상세페이지 프로젝트입니다.",
    overview: [
      "초반 제품 컷과 중간 정보성 섹션, 후반 사용 맥락 컷이 분리되지 않도록 전체 흐름을 하나의 세로형 페이지로 정리했습니다.",
      "브랜드 소개, 제품 설명, 판매 페이지 전개에 모두 대응할 수 있도록 다양한 비율의 이미지를 같은 톤으로 묶었습니다.",
    ],
    credits: [
      ["Client", "르플레르"],
      ["Brand", "르플레르 구강 스프레이"],
      ["Format", "상세페이지 / 브랜드 비주얼"],
      ["Category", "이미지"],
    ],
    coverImage: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-01.webp",
    coverAlt: "르플레르 구강 스프레이 상세페이지 대표 이미지",
    gallery: [
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-01.webp", alt: "르플레르 구강 스프레이 상세페이지 1" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-02.webp", alt: "르플레르 구강 스프레이 상세페이지 2" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-03.webp", alt: "르플레르 구강 스프레이 상세페이지 3" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-04.webp", alt: "르플레르 구강 스프레이 상세페이지 4" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-05.webp", alt: "르플레르 구강 스프레이 상세페이지 5" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-06.webp", alt: "르플레르 구강 스프레이 상세페이지 6" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-07.webp", alt: "르플레르 구강 스프레이 상세페이지 7" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-08.webp", alt: "르플레르 구강 스프레이 상세페이지 8" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-09.webp", alt: "르플레르 구강 스프레이 상세페이지 9" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-10.webp", alt: "르플레르 구강 스프레이 상세페이지 10" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-11.webp", alt: "르플레르 구강 스프레이 상세페이지 11" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-12.webp", alt: "르플레르 구강 스프레이 상세페이지 12" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-13.webp", alt: "르플레르 구강 스프레이 상세페이지 13" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-14.webp", alt: "르플레르 구강 스프레이 상세페이지 14" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-15.webp", alt: "르플레르 구강 스프레이 상세페이지 15" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-16.webp", alt: "르플레르 구강 스프레이 상세페이지 16" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-17.webp", alt: "르플레르 구강 스프레이 상세페이지 17" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-18.webp", alt: "르플레르 구강 스프레이 상세페이지 18" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-19.webp", alt: "르플레르 구강 스프레이 상세페이지 19" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-20.webp", alt: "르플레르 구강 스프레이 상세페이지 20" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-21.webp", alt: "르플레르 구강 스프레이 상세페이지 21" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-22.webp", alt: "르플레르 구강 스프레이 상세페이지 22" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-23.webp", alt: "르플레르 구강 스프레이 상세페이지 23" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-24.webp", alt: "르플레르 구강 스프레이 상세페이지 24" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-25.webp", alt: "르플레르 구강 스프레이 상세페이지 25" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-26.webp", alt: "르플레르 구강 스프레이 상세페이지 26" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-27.webp", alt: "르플레르 구강 스프레이 상세페이지 27" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-28.webp", alt: "르플레르 구강 스프레이 상세페이지 28" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-29.webp", alt: "르플레르 구강 스프레이 상세페이지 29" },
      { src: "/works/projects/lefleur-oral-spray/lefleur-oral-spray-30.webp", alt: "르플레르 구강 스프레이 상세페이지 30" },
    ],
  },
  {
    slug: "haedamchon-gatkimchi",
    itemId: "haedamchon-gatkimchi-detail",
    eyebrow: "이미지 프로젝트",
    client: "해담촌",
    brand: "해담촌 갓김치",
    title: "해담촌 갓김치 상세페이지",
    summary: "해담촌 갓김치의 재료감과 제품 정보를 길게 전달할 수 있도록 구성한 상세페이지 이미지 프로젝트입니다.",
    overview: [
      "세로형 상세페이지 흐름 안에서 제품 특징과 재료 인상이 자연스럽게 이어지도록 화면 전개를 정리했습니다.",
      "판매 페이지에 바로 적용할 수 있도록 텍스트 영역과 비주얼 영역의 밀도를 안정적으로 맞췄습니다.",
    ],
    credits: [
      ["Client", "해담촌"],
      ["Brand", "해담촌 갓김치"],
      ["Format", "상세페이지 / 브랜드 비주얼"],
      ["Category", "이미지"],
    ],
    coverImage: "/works/projects/haedamchon-gatkimchi/haedamchon-gatkimchi-01.webp",
    coverAlt: "해담촌 갓김치 상세페이지 대표 이미지",
    gallery: [
      { src: "/works/projects/haedamchon-gatkimchi/haedamchon-gatkimchi-01.webp", alt: "해담촌 갓김치 상세페이지 1" },
      { src: "/works/projects/haedamchon-gatkimchi/haedamchon-gatkimchi-02.webp", alt: "해담촌 갓김치 상세페이지 2" },
      { src: "/works/projects/haedamchon-gatkimchi/haedamchon-gatkimchi-03.webp", alt: "해담촌 갓김치 상세페이지 3" },
      { src: "/works/projects/haedamchon-gatkimchi/haedamchon-gatkimchi-04.webp", alt: "해담촌 갓김치 상세페이지 4" },
      { src: "/works/projects/haedamchon-gatkimchi/haedamchon-gatkimchi-05.webp", alt: "해담촌 갓김치 상세페이지 5" },
      { src: "/works/projects/haedamchon-gatkimchi/haedamchon-gatkimchi-06.webp", alt: "해담촌 갓김치 상세페이지 6" },
      { src: "/works/projects/haedamchon-gatkimchi/haedamchon-gatkimchi-07.webp", alt: "해담촌 갓김치 상세페이지 7" },
      { src: "/works/projects/haedamchon-gatkimchi/haedamchon-gatkimchi-08.webp", alt: "해담촌 갓김치 상세페이지 8" },
      { src: "/works/projects/haedamchon-gatkimchi/haedamchon-gatkimchi-09.webp", alt: "해담촌 갓김치 상세페이지 9" },
      { src: "/works/projects/haedamchon-gatkimchi/haedamchon-gatkimchi-10.webp", alt: "해담촌 갓김치 상세페이지 10" },
      { src: "/works/projects/haedamchon-gatkimchi/haedamchon-gatkimchi-11.webp", alt: "해담촌 갓김치 상세페이지 11" },
      { src: "/works/projects/haedamchon-gatkimchi/haedamchon-gatkimchi-12.webp", alt: "해담촌 갓김치 상세페이지 12" },
      { src: "/works/projects/haedamchon-gatkimchi/haedamchon-gatkimchi-13.webp", alt: "해담촌 갓김치 상세페이지 13" },
      { src: "/works/projects/haedamchon-gatkimchi/haedamchon-gatkimchi-14.webp", alt: "해담촌 갓김치 상세페이지 14" },
      { src: "/works/projects/haedamchon-gatkimchi/haedamchon-gatkimchi-15.webp", alt: "해담촌 갓김치 상세페이지 15" },
    ],
  },
  {
    slug: "sogalbijjim",
    itemId: "sogalbijjim-detail",
    eyebrow: "이미지 프로젝트",
    client: "행복을 파는 사람들",
    brand: "정성곳간 소갈비찜",
    title: "정성곳간 소갈비찜 상세페이지",
    summary: "정성곳간 소갈비찜의 제품 정보와 푸드 비주얼을 세로형 흐름으로 정리한 상세페이지 프로젝트입니다.",
    overview: [
      "제품 설명과 푸드 컷이 분리되지 않도록 세로형 화면 안에서 정보 전달 흐름을 자연스럽게 이어 붙였습니다.",
      "실제 판매 페이지에 바로 사용할 수 있도록 텍스트 배치와 이미지 구성을 실무형으로 정리했습니다.",
    ],
    credits: [
      ["Client", "행복을 파는 사람들"],
      ["Brand", "정성곳간 소갈비찜"],
      ["Format", "상세페이지 / 브랜드 비주얼"],
      ["Category", "이미지"],
    ],
    coverImage: "/works/projects/sogalbijjim/sogalbijjim-01.webp",
    coverAlt: "정성곳간 소갈비찜 상세페이지 대표 이미지",
    gallery: [
      { src: "/works/projects/sogalbijjim/sogalbijjim-01.webp", alt: "정성곳간 소갈비찜 상세페이지 1" },
      { src: "/works/projects/sogalbijjim/sogalbijjim-02.webp", alt: "정성곳간 소갈비찜 상세페이지 2" },
      { src: "/works/projects/sogalbijjim/sogalbijjim-03.webp", alt: "정성곳간 소갈비찜 상세페이지 3" },
      { src: "/works/projects/sogalbijjim/sogalbijjim-04.webp", alt: "정성곳간 소갈비찜 상세페이지 4" },
      { src: "/works/projects/sogalbijjim/sogalbijjim-05.webp", alt: "정성곳간 소갈비찜 상세페이지 5" },
      { src: "/works/projects/sogalbijjim/sogalbijjim-06.webp", alt: "정성곳간 소갈비찜 상세페이지 6" },
      { src: "/works/projects/sogalbijjim/sogalbijjim-07.webp", alt: "정성곳간 소갈비찜 상세페이지 7" },
      { src: "/works/projects/sogalbijjim/sogalbijjim-08.webp", alt: "정성곳간 소갈비찜 상세페이지 8" },
      { src: "/works/projects/sogalbijjim/sogalbijjim-09.webp", alt: "정성곳간 소갈비찜 상세페이지 9" },
      { src: "/works/projects/sogalbijjim/sogalbijjim-10.webp", alt: "정성곳간 소갈비찜 상세페이지 10" },
      { src: "/works/projects/sogalbijjim/sogalbijjim-11.webp", alt: "정성곳간 소갈비찜 상세페이지 11" },
      { src: "/works/projects/sogalbijjim/sogalbijjim-12.webp", alt: "정성곳간 소갈비찜 상세페이지 12" },
    ],
  },
  {
    slug: "gyeongbuk-educators-ai-workshop",
    itemId: "gyeongbuk-educators-ai-workshop",
    eyebrow: "이미지 프로젝트",
    client: "경북테크노파크",
    brand: "경북 교육자 대상 AI 역량강화 강의",
    title: "경북 교육자 대상 AI 역량강화 강의",
    summary:
      "경북 교육자 대상 AI 역량강화 강의 현장을 기록한 프로젝트로, 현장 분위기와 발표 장면의 집중도를 중심으로 정리한 이미지입니다.",
    overview: [
      "강의 현장의 공기와 참여자 반응이 함께 읽히도록 공간감과 인물 중심 구도를 안정적으로 정리했습니다.",
      "교육 프로그램 소개, 활동 기록, 포트폴리오 아카이브에 바로 사용할 수 있도록 대표 장면을 선별했습니다.",
    ],
    credits: [
      ["Client", "경북테크노파크"],
      ["Brand", "경북 교육자 대상 AI 역량강화 강의"],
      ["Format", "강의 기록 / 행사 스틸"],
      ["Category", "이미지"],
    ],
    coverImage: "/works/projects/gyeongbuk-educators-ai-workshop/gyeongbuk-educators-ai-workshop-01.webp",
    coverAlt: "경북 교육자 대상 AI 역량강화 강의 대표 이미지",
    gallery: [
      {
        src: "/works/projects/gyeongbuk-educators-ai-workshop/gyeongbuk-educators-ai-workshop-01.webp",
        alt: "경북 교육자 대상 AI 역량강화 강의 1",
      },
      {
        src: "/works/projects/gyeongbuk-educators-ai-workshop/gyeongbuk-educators-ai-workshop-02.webp",
        alt: "경북 교육자 대상 AI 역량강화 강의 2",
      },
      {
        src: "/works/projects/gyeongbuk-educators-ai-workshop/gyeongbuk-educators-ai-workshop-03.webp",
        alt: "경북 교육자 대상 AI 역량강화 강의 3",
      },
      {
        src: "/works/projects/gyeongbuk-educators-ai-workshop/gyeongbuk-educators-ai-workshop-04.webp",
        alt: "경북 교육자 대상 AI 역량강화 강의 4",
      },
      {
        src: "/works/projects/gyeongbuk-educators-ai-workshop/gyeongbuk-educators-ai-workshop-05.webp",
        alt: "경북 교육자 대상 AI 역량강화 강의 5",
      },
    ],
  },
  {
    slug: "youngsan-ai-webtoon-lecture",
    itemId: "youngsan-ai-webtoon-lecture",
    eyebrow: "이미지 프로젝트",
    client: "영산대학교",
    brand: "영산대 AI 웹툰 강의",
    title: "영산대 AI 웹툰 강의",
    summary:
      "영산대 AI 웹툰 강의 현장을 기록한 프로젝트로, 강의 공간의 무드와 교육 장면의 흐름을 함께 전달할 수 있도록 정리한 이미지입니다.",
    overview: [
      "발표 화면과 강연자, 현장 분위기가 한 장면 안에서 자연스럽게 이어지도록 시선 흐름을 정리했습니다.",
      "교육 프로그램 소개와 강의 아카이브에 모두 활용할 수 있도록 대표 장면을 중심으로 구성했습니다.",
    ],
    credits: [
      ["Client", "영산대학교"],
      ["Brand", "영산대 AI 웹툰 강의"],
      ["Format", "강의 기록 / 행사 스틸"],
      ["Category", "이미지"],
    ],
    coverImage: "/works/projects/youngsan-ai-webtoon-lecture/youngsan-ai-webtoon-lecture-01.webp",
    coverAlt: "영산대 AI 웹툰 강의 대표 이미지",
    gallery: [
      {
        src: "/works/projects/youngsan-ai-webtoon-lecture/youngsan-ai-webtoon-lecture-01.webp",
        alt: "영산대 AI 웹툰 강의 1",
      },
      {
        src: "/works/projects/youngsan-ai-webtoon-lecture/youngsan-ai-webtoon-lecture-02.webp",
        alt: "영산대 AI 웹툰 강의 2",
      },
      {
        src: "/works/projects/youngsan-ai-webtoon-lecture/youngsan-ai-webtoon-lecture-03.webp",
        alt: "영산대 AI 웹툰 강의 3",
      },
    ],
  },
  {
    slug: "rise-vfx-hackathon-ai-screening",
    itemId: "rise-vfx-hackathon-ai-screening",
    eyebrow: "이미지 프로젝트",
    client: "제주한라대학교",
    brand: "RISE 사업특수효과(VFX) 해커톤 및 AI 상영",
    title: "RISE 사업특수효과(VFX) 해커톤 및 AI 상영",
    summary:
      "RISE 사업특수효과(VFX) 해커톤 및 AI 상영 현장을 기록한 프로젝트로, 현장 토크와 행사 무드를 세로 구도 안에서 집중감 있게 정리한 이미지입니다.",
    overview: [
      "연사와 참가자, 현장 배경이 함께 읽히도록 세로형 장면의 밀도를 유지하면서 대표 순간을 선별했습니다.",
      "행사 소개, 교육 성과 공유, 포트폴리오 기록에 바로 사용할 수 있도록 현장 분위기가 분명한 컷으로 정리했습니다.",
    ],
    credits: [
      ["Client", "제주한라대학교"],
      ["Brand", "RISE 사업특수효과(VFX) 해커톤 및 AI 상영"],
      ["Format", "행사 기록 / 패널 토크 스틸"],
      ["Category", "이미지"],
    ],
    coverImage: "/works/projects/rise-vfx-hackathon-ai-screening/rise-vfx-hackathon-ai-screening-01.webp",
    coverAlt: "RISE 사업특수효과(VFX) 해커톤 및 AI 상영 대표 이미지",
    gallery: [
      {
        src: "/works/projects/rise-vfx-hackathon-ai-screening/rise-vfx-hackathon-ai-screening-01.webp",
        alt: "RISE 사업특수효과(VFX) 해커톤 및 AI 상영 1",
      },
      {
        src: "/works/projects/rise-vfx-hackathon-ai-screening/rise-vfx-hackathon-ai-screening-02.webp",
        alt: "RISE 사업특수효과(VFX) 해커톤 및 AI 상영 2",
      },
      {
        src: "/works/projects/rise-vfx-hackathon-ai-screening/rise-vfx-hackathon-ai-screening-03.webp",
        alt: "RISE 사업특수효과(VFX) 해커톤 및 AI 상영 3",
      },
      {
        src: "/works/projects/rise-vfx-hackathon-ai-screening/rise-vfx-hackathon-ai-screening-04.webp",
        alt: "RISE 사업특수효과(VFX) 해커톤 및 AI 상영 4",
      },
      {
        src: "/works/projects/rise-vfx-hackathon-ai-screening/rise-vfx-hackathon-ai-screening-05.webp",
        alt: "RISE 사업특수효과(VFX) 해커톤 및 AI 상영 5",
      },
      {
        src: "/works/projects/rise-vfx-hackathon-ai-screening/rise-vfx-hackathon-ai-screening-06.webp",
        alt: "RISE 사업특수효과(VFX) 해커톤 및 AI 상영 6",
      },
    ],
  },
];

export function getWorkDetailBySlug(slug) {
  const detail = workDetails.find((entry) => entry.slug === slug);

  if (!detail) {
    return null;
  }

  const item = worksItems.find((entry) => entry.id === detail.itemId);

  if (!item) {
    return null;
  }

  const sortedGallery = [...detail.gallery].sort((left, right) =>
    left.src.localeCompare(right.src, undefined, {
      numeric: true,
      sensitivity: "base",
    }),
  );

  return { ...item, ...detail, gallery: sortedGallery };
}
