export const worksFilters = [
  { id: "all", label: "All" },
  { id: "photography", label: "Photography" },
  { id: "cinematography", label: "Cinematography" },
];

export const worksItems = [
  {
    id: "revv-campaign-visual",
    detailSlug: "revv",
    category: "photography",
    kind: "image",
    aspect: "1:1",
    className: "card-feature",
    typeLabel: "Photography",
    title: "REVV 올리비아로렌 브랜드 런웨이",
    imageSrc: "/works/image/REVV.jpg",
    imageAlt: "REVV 올리비아로렌 브랜드 런웨이 대표 이미지",
  },
  {
    id: "moneyism-ai-teaser",
    category: "cinematography",
    kind: "video",
    aspect: "9:16",
    className: "card-video",
    typeLabel: "Cinematography",
    title: "샤MONEY즘 AI 실사화",
    videoSrc: "/works/video/moneyism-teaser.webm",
    href: "https://www.youtube.com/shorts/aocSdGRn2nI",
    ariaLabel: "샤MONEY즘 AI 실사화 영상 열기",
  },
  {
    id: "saerom-herbal-beauty-cut",
    detailSlug: "saerom-black-goat-beauty-cut",
    category: "photography",
    kind: "image",
    aspect: "4:3",
    className: "card-dark card-photo",
    typeLabel: "Photography",
    title: "새롬한방 흑염소진액 뷰티컷",
    imageSrc: "/works/image/saerom-black-goat-beauty-cut.jpg",
    imageAlt: "새롬한방 흑염소진액 뷰티컷",
  },
  {
    id: "richcoco-beauty-cut",
    detailSlug: "richcoco",
    category: "photography",
    kind: "image",
    aspect: "4:3",
    className: "card-photo",
    typeLabel: "Photography",
    title: "리치코코 뷰티컷",
    imageSrc: "/works/projects/richcoco/richcoco-01.webp",
    imageAlt: "리치코코 뷰티컷 대표 이미지",
  },
  {
    id: "galbitsal-beauty-cut",
    detailSlug: "galbitsal",
    category: "photography",
    kind: "image",
    aspect: "16:9",
    className: "card-photo",
    typeLabel: "Photography",
    title: "갈빗살 뷰티컷",
    imageSrc: "/works/projects/galbitsal/galbitsal-01.webp",
    imageAlt: "갈빗살 뷰티컷 대표 이미지",
  },
  {
    id: "blueberry-beauty-cut",
    detailSlug: "blueberry",
    category: "photography",
    kind: "image",
    aspect: "9:16",
    className: "card-photo",
    typeLabel: "Photography",
    title: "블루베리 뷰티컷",
    imageSrc: "/works/projects/blueberry/blueberry-01.webp",
    imageAlt: "블루베리 뷰티컷 대표 이미지",
  },
  {
    id: "ssanghwa-beauty-cut",
    detailSlug: "ssanghwa",
    category: "photography",
    kind: "image",
    aspect: "9:16",
    className: "card-photo",
    typeLabel: "Photography",
    title: "쌍화진액 뷰티컷",
    imageSrc: "/works/projects/ssanghwa/ssanghwa-01.webp",
    imageAlt: "쌍화진액 뷰티컷 대표 이미지",
  },
  {
    id: "suji-tang-beauty-cut",
    detailSlug: "suji-tang",
    category: "photography",
    kind: "image",
    aspect: "4:3",
    className: "card-photo",
    typeLabel: "Photography",
    title: "스지탕 뷰티컷",
    imageSrc: "/works/projects/suji-tang/suji-tang-01.webp",
    imageAlt: "스지탕 뷰티컷 대표 이미지",
  },
  {
    id: "prune-noni-beauty-cut",
    detailSlug: "prune-noni",
    category: "photography",
    kind: "image",
    aspect: "4:3",
    className: "card-photo",
    typeLabel: "Photography",
    title: "푸룬노니 뷰티컷",
    imageSrc: "/works/projects/prune-noni/prune-noni-01.webp",
    imageAlt: "푸룬노니 뷰티컷 대표 이미지",
  },
  {
    id: "hanwoo-bulgogi-beauty-cut",
    detailSlug: "hanwoo-bulgogi",
    category: "photography",
    kind: "image",
    aspect: "4:3",
    className: "card-photo",
    typeLabel: "Photography",
    title: "한우뚝배기불고기 뷰티컷",
    imageSrc: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-01.webp",
    imageAlt: "한우뚝배기불고기 뷰티컷 대표 이미지",
  },
  {
    id: "black-goat-soup-beauty-cut",
    detailSlug: "black-goat-soup",
    category: "photography",
    kind: "image",
    aspect: "4:3",
    className: "card-photo",
    typeLabel: "Photography",
    title: "흑염소탕 뷰티컷",
    imageSrc: "/works/projects/black-goat-soup/black-goat-soup-01.webp",
    imageAlt: "흑염소탕 뷰티컷 대표 이미지",
  },
  {
    id: "gen-ai-seoul-opening",
    category: "cinematography",
    kind: "video",
    aspect: "16:9",
    className: "card-video-inline",
    typeLabel: "Cinematography",
    title: "GEN AI SEOUL 2025 오프닝",
    videoSrc: "/works/video/gen-ai-seoul-opening.webm",
    href: "https://youtu.be/XtWxe_S7nt4?si=CIl-Scs84aEHoB0q",
    ariaLabel: "GEN AI SEOUL 2025 오프닝 영상 열기",
  },
  {
    id: "kbs-2025-promo-film",
    category: "cinematography",
    kind: "video",
    aspect: "16:9",
    className: "card-soft card-video-wide",
    typeLabel: "Cinematography",
    title: "KBS 2025 홍보 영상",
    videoSrc: "/works/video/kbs-happy-future.webm",
    href: "https://youtu.be/av9kFpHjj08?si=dofwsG8FSgxsT6oi",
    ariaLabel: "KBS 홍보 영상 열기",
  },
  {
    id: "naver-webtoon-ai-teaser",
    category: "cinematography",
    kind: "video",
    aspect: "9:16",
    className: "card-video-tall",
    typeLabel: "Cinematography",
    title: "네이버 웹툰 별정직 공무원 AI 실사화",
    videoSrc: "/works/video/naver-webtoon-ai-teaser.webm",
    href: "https://www.youtube.com/shorts/Ud1OrxerwE4",
    ariaLabel: "네이버웹툰 별정직공무원 AI 티저 열기",
  },
];

export const workDetails = [
  {
    slug: "revv",
    itemId: "revv-campaign-visual",
    eyebrow: "Photography Project",
    client: "올리비아로렌",
    brand: "REVV",
    title: "REVV 올리비아로렌 브랜드 런웨이",
    summary:
      "브랜드 런웨이 무드를 패션 비주얼 중심으로 정리한 프로젝트로, 룩의 존재감과 무대 인상을 동시에 보여주는 이미지를 구성했습니다.",
    overview: [
      "패션 실루엣과 조명 대비를 중심으로, 룩 자체의 인상이 먼저 전달되도록 장면을 정리했습니다.",
      "룩북, 캠페인 소개, 브랜드 아카이브에 바로 연결할 수 있도록 톤과 컷 구성을 통일감 있게 맞췄습니다.",
    ],
    credits: [
      ["Client", "올리비아로렌"],
      ["Brand", "REVV"],
      ["Format", "브랜드 런웨이 / 패션 비주얼"],
      ["Category", "Photography"],
    ],
    coverImage: "/works/projects/revv/revv-look-01.webp",
    coverAlt: "REVV 올리비아로렌 브랜드 런웨이 대표 컷",
    gallery: [
      { src: "/works/projects/revv/revv-look-01.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 1" },
      { src: "/works/projects/revv/revv-look-02.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 2" },
      { src: "/works/projects/revv/revv-look-03.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 3" },
      { src: "/works/projects/revv/revv-look-04.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 4" },
      { src: "/works/projects/revv/revv-look-05.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 5" },
      { src: "/works/projects/revv/revv-look-06.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 6" },
      { src: "/works/projects/revv/revv-look-07.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 7" },
      { src: "/works/projects/revv/revv-look-08.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 8" },
      { src: "/works/projects/revv/revv-look-09.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 9" },
      { src: "/works/projects/revv/revv-look-10.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 10" },
      { src: "/works/projects/revv/revv-look-11.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 11" },
      { src: "/works/projects/revv/revv-look-12.webp", alt: "REVV 올리비아로렌 브랜드 런웨이 컷 12" },
    ],
  },
  {
    slug: "saerom-black-goat-beauty-cut",
    itemId: "saerom-herbal-beauty-cut",
    eyebrow: "Photography Project",
    client: "행복을 파는 사람들",
    brand: "새롬한방 흑염소진액",
    title: "새롬한방 흑염소진액 뷰티컷",
    summary:
      "전통 한방 원료의 밀도와 제품의 프리미엄 무드를 동시에 보여주기 위해, 재료의 질감과 패키지의 존재감을 중심으로 정리한 비주얼 시리즈입니다.",
    overview: [
      "제품이 단순히 놓여 있는 느낌보다, 흑염소진액이 가진 진중한 인상과 원료의 무게감이 함께 전달되도록 장면을 구성했습니다.",
      "검은 패키지와 한방 재료의 대비를 살리면서, 상세페이지나 판매 채널에서 바로 사용할 수 있는 실무형 컷으로 연결하는 데 집중했습니다.",
    ],
    credits: [
      ["Client", "행복을 파는 사람들"],
      ["Brand", "새롬한방"],
      ["Format", "상세페이지 / 광고용 비주얼"],
      ["Category", "Photography"],
    ],
    coverImage: "/works/projects/saerom/saerom-cut-01.png",
    coverAlt: "새롬한방 흑염소진액 대표 컷",
    gallery: [
      { src: "/works/projects/saerom/saerom-cut-01.png", alt: "새롬한방 흑염소진액 뷰티컷 1" },
      { src: "/works/projects/saerom/saerom-cut-02.png", alt: "새롬한방 흑염소진액 뷰티컷 2" },
      { src: "/works/projects/saerom/saerom-cut-03.png", alt: "새롬한방 흑염소진액 뷰티컷 3" },
      { src: "/works/projects/saerom/saerom-cut-04.png", alt: "새롬한방 흑염소진액 뷰티컷 4" },
      { src: "/works/projects/saerom/saerom-cut-05.png", alt: "새롬한방 흑염소진액 뷰티컷 5" },
      { src: "/works/projects/saerom/saerom-cut-06.png", alt: "새롬한방 흑염소진액 뷰티컷 6" },
      { src: "/works/projects/saerom/saerom-cut-07.png", alt: "새롬한방 흑염소진액 뷰티컷 7" },
      { src: "/works/projects/saerom/saerom-cut-08.png", alt: "새롬한방 흑염소진액 뷰티컷 8" },
      { src: "/works/projects/saerom/saerom-cut-09.png", alt: "새롬한방 흑염소진액 뷰티컷 9" },
      { src: "/works/projects/saerom/saerom-cut-10.png", alt: "새롬한방 흑염소진액 뷰티컷 10" },
    ],
  },
  {
    slug: "richcoco",
    itemId: "richcoco-beauty-cut",
    eyebrow: "Photography Project",
    client: "행복을 파는 사람들",
    brand: "리치코코",
    title: "리치코코 뷰티컷",
    summary: "리치코코 제품의 컬러감과 패키지 무드를 중심으로 정리한 비주얼 시리즈입니다.",
    overview: [
      "제품의 톤과 디저트 무드를 함께 살리면서, 상세페이지와 광고 비주얼에 바로 연결할 수 있는 컷 위주로 구성했습니다.",
      "브랜드의 밝은 인상을 유지하면서도 제품 정보 전달에 방해되지 않도록 배경과 오브젝트 밀도를 정리했습니다.",
    ],
    credits: [
      ["Client", "행복을 파는 사람들"],
      ["Brand", "리치코코"],
      ["Format", "상세페이지 / 광고용 비주얼"],
      ["Category", "Photography"],
    ],
    coverImage: "/works/projects/richcoco/richcoco-01.webp",
    coverAlt: "리치코코 대표 컷",
    gallery: [
      { src: "/works/projects/richcoco/richcoco-01.webp", alt: "리치코코 뷰티컷 1" },
      { src: "/works/projects/richcoco/richcoco-02.webp", alt: "리치코코 뷰티컷 2" },
      { src: "/works/projects/richcoco/richcoco-03.webp", alt: "리치코코 뷰티컷 3" },
      { src: "/works/projects/richcoco/richcoco-04.webp", alt: "리치코코 뷰티컷 4" },
      { src: "/works/projects/richcoco/richcoco-05.webp", alt: "리치코코 뷰티컷 5" },
      { src: "/works/projects/richcoco/richcoco-06.webp", alt: "리치코코 뷰티컷 6" },
      { src: "/works/projects/richcoco/richcoco-07.webp", alt: "리치코코 뷰티컷 7" },
      { src: "/works/projects/richcoco/richcoco-08.webp", alt: "리치코코 뷰티컷 8" },
      { src: "/works/projects/richcoco/richcoco-09.webp", alt: "리치코코 뷰티컷 9" },
      { src: "/works/projects/richcoco/richcoco-10.webp", alt: "리치코코 뷰티컷 10" },
      { src: "/works/projects/richcoco/richcoco-11.webp", alt: "리치코코 뷰티컷 11" },
      { src: "/works/projects/richcoco/richcoco-12.webp", alt: "리치코코 뷰티컷 12" },
      { src: "/works/projects/richcoco/richcoco-13.webp", alt: "리치코코 뷰티컷 13" },
      { src: "/works/projects/richcoco/richcoco-14.webp", alt: "리치코코 뷰티컷 14" },
    ],
  },
  {
    slug: "galbitsal",
    itemId: "galbitsal-beauty-cut",
    eyebrow: "Photography Project",
    client: "행복을 파는 사람들",
    brand: "갈빗살",
    title: "갈빗살 뷰티컷",
    summary: "갈빗살 제품의 식감과 조리 인상을 강하게 보여주기 위해 정리한 상세용 비주얼 시리즈입니다.",
    overview: [
      "완성 컷과 원육 컷을 함께 묶어, 제품의 풍성한 인상과 원재료의 신뢰감을 동시에 전달하도록 구성했습니다.",
      "광고, 판매 페이지, 배너 영역에서 그대로 활용할 수 있도록 컷 간 톤과 밀도를 일정하게 맞췄습니다.",
    ],
    credits: [
      ["Client", "행복을 파는 사람들"],
      ["Brand", "갈빗살"],
      ["Format", "상세페이지 / 광고용 비주얼"],
      ["Category", "Photography"],
    ],
    coverImage: "/works/projects/galbitsal/galbitsal-01.webp",
    coverAlt: "갈빗살 대표 컷",
    gallery: [
      { src: "/works/projects/galbitsal/galbitsal-01.webp", alt: "갈빗살 뷰티컷 1" },
      { src: "/works/projects/galbitsal/galbitsal-02.webp", alt: "갈빗살 뷰티컷 2" },
      { src: "/works/projects/galbitsal/galbitsal-03.webp", alt: "갈빗살 뷰티컷 3" },
      { src: "/works/projects/galbitsal/galbitsal-04.webp", alt: "갈빗살 뷰티컷 4" },
      { src: "/works/projects/galbitsal/galbitsal-05.webp", alt: "갈빗살 뷰티컷 5" },
      { src: "/works/projects/galbitsal/galbitsal-06.webp", alt: "갈빗살 뷰티컷 6" },
      { src: "/works/projects/galbitsal/galbitsal-07.webp", alt: "갈빗살 뷰티컷 7" },
      { src: "/works/projects/galbitsal/galbitsal-08.webp", alt: "갈빗살 뷰티컷 8" },
      { src: "/works/projects/galbitsal/galbitsal-09.webp", alt: "갈빗살 뷰티컷 9" },
      { src: "/works/projects/galbitsal/galbitsal-10.webp", alt: "갈빗살 뷰티컷 10" },
      { src: "/works/projects/galbitsal/galbitsal-11.webp", alt: "갈빗살 뷰티컷 11" },
      { src: "/works/projects/galbitsal/galbitsal-12.webp", alt: "갈빗살 뷰티컷 12" },
      { src: "/works/projects/galbitsal/galbitsal-13.webp", alt: "갈빗살 뷰티컷 13" },
      { src: "/works/projects/galbitsal/galbitsal-14.webp", alt: "갈빗살 뷰티컷 14" },
      { src: "/works/projects/galbitsal/galbitsal-15.webp", alt: "갈빗살 뷰티컷 15" },
      { src: "/works/projects/galbitsal/galbitsal-16.webp", alt: "갈빗살 뷰티컷 16" },
      { src: "/works/projects/galbitsal/galbitsal-17.webp", alt: "갈빗살 뷰티컷 17" },
      { src: "/works/projects/galbitsal/galbitsal-18.webp", alt: "갈빗살 뷰티컷 18" },
      { src: "/works/projects/galbitsal/galbitsal-19.webp", alt: "갈빗살 뷰티컷 19" },
      { src: "/works/projects/galbitsal/galbitsal-20.webp", alt: "갈빗살 뷰티컷 20" },
    ],
  },
  {
    slug: "blueberry",
    itemId: "blueberry-beauty-cut",
    eyebrow: "Photography Project",
    client: "행복을 파는 사람들",
    brand: "블루베리",
    title: "블루베리 뷰티컷",
    summary: "블루베리 제품의 산뜻한 컬러와 음용 이미지를 강조해 정리한 비주얼 시리즈입니다.",
    overview: [
      "제품 컬러와 원재료 무드가 동시에 살아나도록 블루 계열의 인상을 중심으로 컷을 구성했습니다.",
      "모바일 상세페이지나 세로형 광고에도 바로 적용할 수 있도록 세로 컷 흐름을 유지했습니다.",
    ],
    credits: [
      ["Client", "행복을 파는 사람들"],
      ["Brand", "블루베리"],
      ["Format", "상세페이지 / 광고용 비주얼"],
      ["Category", "Photography"],
    ],
    coverImage: "/works/projects/blueberry/blueberry-01.webp",
    coverAlt: "블루베리 대표 컷",
    gallery: [
      { src: "/works/projects/blueberry/blueberry-01.webp", alt: "블루베리 뷰티컷 1" },
      { src: "/works/projects/blueberry/blueberry-02.webp", alt: "블루베리 뷰티컷 2" },
      { src: "/works/projects/blueberry/blueberry-03.webp", alt: "블루베리 뷰티컷 3" },
      { src: "/works/projects/blueberry/blueberry-04.webp", alt: "블루베리 뷰티컷 4" },
      { src: "/works/projects/blueberry/blueberry-05.webp", alt: "블루베리 뷰티컷 5" },
      { src: "/works/projects/blueberry/blueberry-06.webp", alt: "블루베리 뷰티컷 6" },
      { src: "/works/projects/blueberry/blueberry-07.webp", alt: "블루베리 뷰티컷 7" },
      { src: "/works/projects/blueberry/blueberry-08.webp", alt: "블루베리 뷰티컷 8" },
      { src: "/works/projects/blueberry/blueberry-09.webp", alt: "블루베리 뷰티컷 9" },
    ],
  },
  {
    slug: "ssanghwa",
    itemId: "ssanghwa-beauty-cut",
    eyebrow: "Photography Project",
    client: "행복을 파는 사람들",
    brand: "쌍화진액",
    title: "쌍화진액 뷰티컷",
    summary: "쌍화진액 제품의 농도감과 프리미엄 인상을 중심으로 정리한 뷰티컷 시리즈입니다.",
    overview: [
      "누끼컷과 상세 이미지가 아닌 뷰티컷만 선별해, 제품이 가장 설득력 있게 보이는 장면 위주로 구성했습니다.",
      "전통 한방 무드와 현대적인 상품 비주얼 사이 균형을 맞추는 데 집중했습니다.",
    ],
    credits: [
      ["Client", "행복을 파는 사람들"],
      ["Brand", "쌍화진액"],
      ["Format", "상세페이지 / 광고용 비주얼"],
      ["Category", "Photography"],
    ],
    coverImage: "/works/projects/ssanghwa/ssanghwa-01.webp",
    coverAlt: "쌍화진액 대표 컷",
    gallery: [
      { src: "/works/projects/ssanghwa/ssanghwa-01.webp", alt: "쌍화진액 뷰티컷 1" },
      { src: "/works/projects/ssanghwa/ssanghwa-02.webp", alt: "쌍화진액 뷰티컷 2" },
      { src: "/works/projects/ssanghwa/ssanghwa-03.webp", alt: "쌍화진액 뷰티컷 3" },
      { src: "/works/projects/ssanghwa/ssanghwa-04.webp", alt: "쌍화진액 뷰티컷 4" },
      { src: "/works/projects/ssanghwa/ssanghwa-05.webp", alt: "쌍화진액 뷰티컷 5" },
      { src: "/works/projects/ssanghwa/ssanghwa-06.webp", alt: "쌍화진액 뷰티컷 6" },
      { src: "/works/projects/ssanghwa/ssanghwa-07.webp", alt: "쌍화진액 뷰티컷 7" },
      { src: "/works/projects/ssanghwa/ssanghwa-08.webp", alt: "쌍화진액 뷰티컷 8" },
      { src: "/works/projects/ssanghwa/ssanghwa-09.webp", alt: "쌍화진액 뷰티컷 9" },
      { src: "/works/projects/ssanghwa/ssanghwa-10.webp", alt: "쌍화진액 뷰티컷 10" },
    ],
  },
  {
    slug: "suji-tang",
    itemId: "suji-tang-beauty-cut",
    eyebrow: "Photography Project",
    client: "행복을 파는 사람들",
    brand: "스지탕",
    title: "스지탕 뷰티컷",
    summary: "스지탕의 온기와 재료감을 중심으로 구성한 푸드 비주얼 시리즈입니다.",
    overview: [
      "누끼컷은 제외하고 완성된 장면 중심의 뷰티컷만 선별해, 제품 사용처에서 바로 활용하기 쉬운 흐름으로 정리했습니다.",
      "국물의 깊이감과 재료의 존재감이 자연스럽게 전달되도록 색과 대비를 맞췄습니다.",
    ],
    credits: [
      ["Client", "행복을 파는 사람들"],
      ["Brand", "스지탕"],
      ["Format", "상세페이지 / 광고용 비주얼"],
      ["Category", "Photography"],
    ],
    coverImage: "/works/projects/suji-tang/suji-tang-01.webp",
    coverAlt: "스지탕 대표 컷",
    gallery: [
      { src: "/works/projects/suji-tang/suji-tang-01.webp", alt: "스지탕 뷰티컷 1" },
      { src: "/works/projects/suji-tang/suji-tang-02.webp", alt: "스지탕 뷰티컷 2" },
      { src: "/works/projects/suji-tang/suji-tang-03.webp", alt: "스지탕 뷰티컷 3" },
      { src: "/works/projects/suji-tang/suji-tang-04.webp", alt: "스지탕 뷰티컷 4" },
      { src: "/works/projects/suji-tang/suji-tang-05.webp", alt: "스지탕 뷰티컷 5" },
      { src: "/works/projects/suji-tang/suji-tang-06.webp", alt: "스지탕 뷰티컷 6" },
      { src: "/works/projects/suji-tang/suji-tang-07.webp", alt: "스지탕 뷰티컷 7" },
      { src: "/works/projects/suji-tang/suji-tang-08.webp", alt: "스지탕 뷰티컷 8" },
      { src: "/works/projects/suji-tang/suji-tang-09.webp", alt: "스지탕 뷰티컷 9" },
      { src: "/works/projects/suji-tang/suji-tang-10.webp", alt: "스지탕 뷰티컷 10" },
      { src: "/works/projects/suji-tang/suji-tang-11.webp", alt: "스지탕 뷰티컷 11" },
    ],
  },
  {
    slug: "prune-noni",
    itemId: "prune-noni-beauty-cut",
    eyebrow: "Photography Project",
    client: "행복을 파는 사람들",
    brand: "푸룬노니",
    title: "푸룬노니 뷰티컷",
    summary: "푸룬노니 제품의 건강한 무드와 컬러 인상을 중심으로 정리한 비주얼 시리즈입니다.",
    overview: [
      "과일 원료와 제품 패키지가 함께 살아나도록 무드를 맞추고, 상품 판매 페이지에 바로 적용 가능한 장면 위주로 구성했습니다.",
      "움직이는 컷이 아닌 정적인 뷰티컷만 선별해 프로젝트 흐름을 단순하게 정리했습니다.",
    ],
    credits: [
      ["Client", "행복을 파는 사람들"],
      ["Brand", "푸룬노니"],
      ["Format", "상세페이지 / 광고용 비주얼"],
      ["Category", "Photography"],
    ],
    coverImage: "/works/projects/prune-noni/prune-noni-01.webp",
    coverAlt: "푸룬노니 대표 컷",
    gallery: [
      { src: "/works/projects/prune-noni/prune-noni-01.webp", alt: "푸룬노니 뷰티컷 1" },
      { src: "/works/projects/prune-noni/prune-noni-02.webp", alt: "푸룬노니 뷰티컷 2" },
      { src: "/works/projects/prune-noni/prune-noni-03.webp", alt: "푸룬노니 뷰티컷 3" },
      { src: "/works/projects/prune-noni/prune-noni-04.webp", alt: "푸룬노니 뷰티컷 4" },
      { src: "/works/projects/prune-noni/prune-noni-05.webp", alt: "푸룬노니 뷰티컷 5" },
      { src: "/works/projects/prune-noni/prune-noni-06.webp", alt: "푸룬노니 뷰티컷 6" },
      { src: "/works/projects/prune-noni/prune-noni-07.webp", alt: "푸룬노니 뷰티컷 7" },
      { src: "/works/projects/prune-noni/prune-noni-08.webp", alt: "푸룬노니 뷰티컷 8" },
      { src: "/works/projects/prune-noni/prune-noni-09.webp", alt: "푸룬노니 뷰티컷 9" },
    ],
  },
  {
    slug: "hanwoo-bulgogi",
    itemId: "hanwoo-bulgogi-beauty-cut",
    eyebrow: "Photography Project",
    client: "행복을 파는 사람들",
    brand: "한우뚝배기불고기",
    title: "한우뚝배기불고기 뷰티컷",
    summary: "한우뚝배기불고기 제품의 푸드 임팩트와 완성 컷 무드를 중심으로 구성한 프로젝트입니다.",
    overview: [
      "완성 음식의 풍부한 인상이 먼저 전달되도록 장면을 정리하고, 판매용 페이지에 바로 연결 가능한 컷 흐름으로 구성했습니다.",
      "누끼컷은 제외하고 푸드 연출이 살아 있는 뷰티컷만 사용해 프로젝트 성격을 분명하게 정리했습니다.",
    ],
    credits: [
      ["Client", "행복을 파는 사람들"],
      ["Brand", "한우뚝배기불고기"],
      ["Format", "상세페이지 / 광고용 비주얼"],
      ["Category", "Photography"],
    ],
    coverImage: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-01.webp",
    coverAlt: "한우뚝배기불고기 대표 컷",
    gallery: [
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-01.webp", alt: "한우뚝배기불고기 뷰티컷 1" },
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-02.webp", alt: "한우뚝배기불고기 뷰티컷 2" },
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-03.webp", alt: "한우뚝배기불고기 뷰티컷 3" },
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-04.webp", alt: "한우뚝배기불고기 뷰티컷 4" },
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-05.webp", alt: "한우뚝배기불고기 뷰티컷 5" },
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-06.webp", alt: "한우뚝배기불고기 뷰티컷 6" },
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-07.webp", alt: "한우뚝배기불고기 뷰티컷 7" },
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-08.webp", alt: "한우뚝배기불고기 뷰티컷 8" },
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-09.webp", alt: "한우뚝배기불고기 뷰티컷 9" },
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-10.webp", alt: "한우뚝배기불고기 뷰티컷 10" },
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-11.webp", alt: "한우뚝배기불고기 뷰티컷 11" },
      { src: "/works/projects/hanwoo-bulgogi/hanwoo-bulgogi-12.webp", alt: "한우뚝배기불고기 뷰티컷 12" },
    ],
  },
  {
    slug: "black-goat-soup",
    itemId: "black-goat-soup-beauty-cut",
    eyebrow: "Photography Project",
    client: "행복을 파는 사람들",
    brand: "흑염소탕",
    title: "흑염소탕 뷰티컷",
    summary: "흑염소탕 제품의 묵직한 인상과 국물의 깊이를 살려 구성한 비주얼 시리즈입니다.",
    overview: [
      "누끼컷은 제외하고 실제 사용 장면에 가까운 뷰티컷만 선별해 프로젝트 흐름을 정리했습니다.",
      "한방 보양식의 무게감이 자연스럽게 전달되도록 어두운 톤과 재료감을 중심으로 컷을 구성했습니다.",
    ],
    credits: [
      ["Client", "행복을 파는 사람들"],
      ["Brand", "흑염소탕"],
      ["Format", "상세페이지 / 광고용 비주얼"],
      ["Category", "Photography"],
    ],
    coverImage: "/works/projects/black-goat-soup/black-goat-soup-01.webp",
    coverAlt: "흑염소탕 대표 컷",
    gallery: [
      { src: "/works/projects/black-goat-soup/black-goat-soup-01.webp", alt: "흑염소탕 뷰티컷 1" },
      { src: "/works/projects/black-goat-soup/black-goat-soup-02.webp", alt: "흑염소탕 뷰티컷 2" },
      { src: "/works/projects/black-goat-soup/black-goat-soup-03.webp", alt: "흑염소탕 뷰티컷 3" },
      { src: "/works/projects/black-goat-soup/black-goat-soup-04.webp", alt: "흑염소탕 뷰티컷 4" },
      { src: "/works/projects/black-goat-soup/black-goat-soup-05.webp", alt: "흑염소탕 뷰티컷 5" },
      { src: "/works/projects/black-goat-soup/black-goat-soup-06.webp", alt: "흑염소탕 뷰티컷 6" },
      { src: "/works/projects/black-goat-soup/black-goat-soup-07.webp", alt: "흑염소탕 뷰티컷 7" },
      { src: "/works/projects/black-goat-soup/black-goat-soup-08.webp", alt: "흑염소탕 뷰티컷 8" },
      { src: "/works/projects/black-goat-soup/black-goat-soup-09.webp", alt: "흑염소탕 뷰티컷 9" },
      { src: "/works/projects/black-goat-soup/black-goat-soup-10.webp", alt: "흑염소탕 뷰티컷 10" },
    ],
  },
];

export function getWorkDetailBySlug(slug) {
  const detail = workDetails.find((entry) => entry.slug === slug);

  if (!detail) {
    return null;
  }

  const item = worksItems.find((entry) => entry.id === detail.itemId);

  if (!item) {
    return null;
  }

  return { ...item, ...detail };
}
